### ISSUE TITLE
Signal Strength question

### ISSUE THREAD

**Issue by JavaWiz1** [jeffreydwalter/arlo#104]
Not an issue, a question...
First off, thank you for the work on engineering this API.  I've found it easy to understand and implement.

I am creating a [Kodi ](http://kodi.tv)plugin to allow users to list their Arlo camera's and display the streams in the Kodi interface.  I want to list the signal strength for each camera.  The API returns an integer, on my system 2 for one camera, 4 for the other.

My question is with is the signal strength range (i.e. 0-5)?  A number doesn't really indicate how good the signal is, unless I know what the min and max values are...

Any idea?

**Comment by jeffreydwalter** [comment]
@JavaWiz1 thanks for the kind words.

Unfortunately, I don't know what the range is. One way you might be able to test is to check your camera's signal in the mobile (or desktop) app and move your camera around to lower or raise the signal. When you get the signal at the max, you could use this library to query and see what the number is. Then do the same then when the signal is at its lowest.

If you do that, please do report back so I can add that to the documentation.

Thanks,
Jeff

**Comment by jeffreydwalter** [comment]
@JavaWiz1 did you have any luck with this?

**Comment by JavaWiz1** [comment]
Sorry it's taken so long, my 'real' job got in the way :).   

I did as you suggested, and moved the camera around to various locations.  For my testing, the range was from 2-4.
Results:

- 4: Camera was right next to the base station or within 50ft (with walls)
- 3: A few rooms away from base station, roughly 50-100ft (with walls)
- 2: farthest point in house or garage 100+.  I even took it to end of driveway ~200ft, it still streamed.

I actually didn't take it onto my neighbors property to see if I could get a 1, but I suspect that would have happened.

Based on this, I'm assuming, with my cameras/base station, the range is from 0-4, with 4 being the best reception.
