### ISSUE TITLE
schedule mode code problem.

### ISSUE THREAD

**Issue by pocupine** [jeffreydwalter/arlo#106]
Sorry guys, I am not a IT guy and I am new on python.
My question is pretty straight away.
arlo.Arm(basestations[0]) and arlo.Disarm(basestations[0]) worked
but 
Calendar()
Calendar(basestation, active=True)
Calendar(basestation[0], active=True)
arlo.Calendar(basestation[0], active=True)
etc.
None of them worked. I tried more than an hour.
Someone please help the right format to use this in python scripts.
Thanks so much.

Regards
Clement

**Comment by jeffreydwalter** [comment]
Hello Clement, can you please describe what you're trying to accomplish and include your sample code so I can help you fix the problem.

**Comment by jeffreydwalter** [comment]
You might try, 
```
arlo.Calendar(basestations[0], True)
```

**Comment by pocupine** [comment]
Hi Jeff,

Thanks for your effort to make arlo worked with openHAB. It was an ongoing problem many years for me to change the mode. 

I also tried
arlo.Calendar(basestations[0], True)
arlo.Calendar(basestations[0], True) without space before True
Calendar(basestations[0], True)
Calendar(basestations[0], True) without space before True
But none of them worked. Arm and disarm worked well.

My entire code is same as your sample.


from Arlo import Arlo

USERNAME = 'xxx@gmail.com'
PASSWORD = 'xxx'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	basestations = arlo.GetDevices('basestation')

	# Arm Arlo.
	#arlo.Arm(basestations[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(basestations[0])
      Calendar(basestations[0],True)

except Exception as e:
    print(e)

**Comment by pocupine** [comment]
to make it more completed, I use it on openHAB.
sitemap file:
                Switch item=arlo_arm label="Arlo arm"
		Switch item=arlo_disarm label="Arlo disarm"
		Switch item=arlo_schedule label="Arlo schedule"
rule file:
   rule "arlo_schedule"
   when
        Item arlo_schedule received command
   then
            executeCommandLine("/volume1/@appstore/python3/usr/bin/./python3 /volume1/SmartHome       /openHAB/conf/scripts/arloschedule.py")
   end

items:
Switch arlo_arm "arlo_arm" [ "Switchable" ]
Switch arlo_disarm "arlo_disarm" [ "Switchable" ]
Switch arlo_schedule "arlo_schedule" [ "Switchable" ]

python scripts:
```
from Arlo import Arlo

USERNAME = 'xx@xx'
PASSWORD = 'xxx'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	basestations = arlo.GetDevices('basestation')

	# Arm Arlo.
	#arlo.Arm(basestations[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(basestations[0])
        arlo.Calendar(basestations[0],True)

except Exception as e:
    print(e)
```

**Comment by pocupine** [comment]
I tried to find the compatible model of base station  but failed.  I use arlo pro basestation if that helps.
Since the API includes Siren so I would think it is compatible.

**Comment by jeffreydwalter** [comment]
Netgear has been changing their API lately... `Calendar()` still seems to set the `active` property, which you can see if you call `GetCalendar()` after calling `Calendar()`. I don't really see that call being made anymore when I switch to a schedule in the web UI, so it's probably not needed anymore.

It appears that they just call the `https://arlo.netgear.com/hmsweb/users/devices/automation/active` endpoint and set `activeSchedules` to the array of schedule ids.

Here's the data they pass: 

Set a non-schedule mode to be active:
```
{"activeAutomations":[{"deviceId":"XXXXXXXXXXXXX","timestamp":1532015622105,"activeModes":["mode1"],"activeSchedules":[]}]}
```

Set a schedule to be active:
```
{"activeAutomations":[{"deviceId":"XXXXXXXXXXXXX","timestamp":1532015790139,"activeModes":[],"activeSchedules":["schedule.1"]}]}
```

You should be able to mimic this behavior using the `CustomMode(self, device, mode, schedules=[])` API in this library.

Like this:
```
self.CustomMode(basestations[0], mode=None, schedules=['schedules.1']) # 'schedules.1' is the id of my default schedule."
```

**Comment by jeffreydwalter** [comment]
I updated the example in the wiki to demonstrate setting a schedule, see: https://github.com/jeffreydwalter/arlo/wiki/Changing-Basestation-Modes-(Armed,-Disarmed,-Schedule,-etc.)

**Comment by jeffreydwalter** [comment]
@pocupine also, please update your arlo package to the latest version (there have been several changes made today). Thanks.

You can do that like so: `pip install --upgrade arlo`

**Comment by pocupine** [comment]
I don't know all these codes mean but now, even
arlo.Arm(basestations[0])
arlo.Disarm(basestations[0])
stopped working.

**Comment by jeffreydwalter** [comment]
Are you getting any errors? If you can't provide more context, I can't help you.

**Comment by jeffreydwalter** [comment]
Please provide the output of the following commands: `pip freeze` and `pip3 freeze`

**Comment by pocupine** [comment]
pip freeze:
arlo==1.2.17
bcrypt==3.1.4
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
enum34==1.1.6
idna==2.8
ipaddress==1.0.22
lxml==4.2.5
MarkupSafe==1.1.0
monotonic==1.5
msgpack-python==0.5.6
olefile==0.46
psutil==5.4.8
pyasn1==0.4.4
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pyOpenSSL==18.0.0
PySocks==1.6.8
PyYAML==3.13
requests==2.21.0
ruamel.yaml==0.15.78
six==1.12.0
SQLAlchemy==1.2.10
sseclient==0.0.22
urllib3==1.24.1
virtualenv==16.1.0
zope.interface==4.6.0
You are using pip version 9.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

pip3 freeze returned with no module.

**Comment by jeffreydwalter** [comment]
The code works for me. Are you getting any errors? Can you please paste the code you're running, which is not working? Thanks.

**Comment by pocupine** [comment]
from Arlo import Arlo

USERNAME = 'xx@gmail.com'
PASSWORD = 'xx'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	# Get the list of devices and filter on device type to only get the basestation.
	# This will return an array which includes all of the basestation's associated metadata.
	basestations = arlo.GetDevices('basestation')

	# Arm Arlo.
	arlo.Arm(basestations[0])
	# Or
	# Disarm Arlo.
	# arlo.Disarm(basestations[0])
        # Or
        # Change Mode to some custom mode you created.
        # arlo.CustomMode(basestations[0], "mode3") # 'mode3' is the id of a custom mode you created.
        # Or
        # Change Mode to Schedule.
        # arlo.CustomMode(basestations[0], mode=None, schedules=['schedules.1']) # 'schedules.1' is the id of my default schedule."

except Exception as e:
    print(e)


I actually didn't change this *.py file at all. After upgrade the arlo module, it just died.

**Comment by jeffreydwalter** [comment]
Change the import statement to `from arlo import Arlo`

**Comment by pocupine** [comment]
Hi,
This works. Thanks.
Do I just use the below if I only have 1 schedule?  
arlo.CustomMode(basestations[0], mode=None, schedules=['schedules.1']) # 'schedules.1' is the id of my default schedule."

**Comment by jeffreydwalter** [comment]
`arlo.CustomMode(basestations[0], schedules=['schedules.1'])` should be enough. Assuming that your schedule id = `schedules.1`.

**Comment by pocupine** [comment]
Hi Jeff,

To keep it consistent, I think it is better to modify the arlo module changing the arlo back to Arlo otherwise most people won't realize this change. Thanks so much for your great work and sorry 
for the newbie questions. Have a good day.

Regards
Clement

**Comment by pocupine** [comment]
Hi Jeff,
Sorry. I still have problem to get the schedule id. Do I use arlo.GetModes,arlo.GetModesV2 to get the ID?
I tried arlo.CustomMode(basestations[0], mode=None, schedules=['schedules.1'])
arlo.CustomMode(basestations[0], mode=None,schedules=['schedules.1'])
arlo.CustomMode(basestations[0], mode=None, schedules=['schedule'])
arlo.CustomMode(basestations[0], mode=None,schedules=['schedule'])
without success. 
'schedule' is the ID I get when I login Arlo web portal.
Thanks.

**Comment by pocupine** [comment]
Hi,
I used GetModesV2 and get the below result:
arloschedule.py
[{'gatewayId': '4R026B7BA7892', 'uniqueId': 'N86RSRS-114-8193457_4R026B7BA7892', 'type': 'activeAutomations', 'activeSchedules': ['schedule.1'], 'schemaVersion': 1, 'activeModes': [], 'timestamp': 1549024963798}]

I then used
arlo.CustomMode(basestations[0], mode=none, schedules=['schedule.1'])   and
arlo.CustomMode(basestations[0], schedules=['schedule.1']) 
both didn't work.

Any idea why this happened? Thanks.
