### ISSUE TITLE
CustomMode() / GetModes() Throwing error

### ISSUE THREAD

**Issue by zemerick1** [jeffreydwalter/arlo#107]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 3.7.1

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Windows 10 x64

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.2.9
beautifulsoup4==4.6.3
certifi==2018.10.15
chardet==3.0.4
idna==2.7
monotonic==1.5
Pillow==5.3.0
pyarlo==0.2.3
PySocks==1.6.8
requests==2.20.1
simplejson==3.16.0
six==1.11.0
sseclient==0.0.22
sseclient-py==1.7
urllib3==1.24.1

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo 1st gen wire-free

### What did you do?
USERNAME = 'REDACTED'
PASSWORD = 'REDACTED'

	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    basestations = arlo.GetDevices('basestation')
    print(basestations) 
    print(arlo.GetModes(basestations[0])) 
    arlo.CustomMode(basestations[0], 'test') 
    print(arlo.GetModesV2())

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

### What did you expect to see?
Basestation info
List of available modes
(switch mode)
[Tried an alternative function to try to get it working]

### What did you see instead?
C:\Users\888\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/888/PycharmProjects/untitled/venv/Change_mode.py
Exception ignored in: <function EventStream.__del__ at 0x03AAC198>
Failed to subscribe to eventstream: __init__() got an unexpected keyword argument 'session'
Traceback (most recent call last):
  File "C:\Users\888\PycharmProjects\untitled\venv\lib\site-packages\Arlo.py", line 62, in __del__
    self.Disconnect()
  File "C:\Users\888\PycharmProjects\untitled\venv\lib\site-packages\Arlo.py", line 102, in Disconnect
    self.Unregister()
  File "C:\Users\888\PycharmProjects\untitled\venv\lib\site-packages\Arlo.py", line 119, in Unregister
    if self.event_stream_thread != threading.current_thread():
AttributeError: 'EventStream' object has no attribute 'event_stream_thread'

### Does this issue reproduce with the latest release?

Yes.
******EDIT******
I wanted to add that GetModes() commented out and running just CustomMode() I get the same error.

**Comment by jeffreydwalter** [comment]
Please uninstall `sseclient-py`.

From your `pip freeze`
``
sseclient==0.0.22
sseclient-py==1.7
``

**Comment by zemerick1** [comment]
I should have seen that. My bad. 

Thanks. I do have a real issue I believe. I'll start a new thread.
