### ISSUE TITLE
Name 'requests' is not defined

### ISSUE THREAD

**Issue by rnorth** [jeffreydwalter/arlo#109]
Thanks for this useful library! I've encountered what is probably just a simple issue affecting the latest versions.

### What version of Python are you using (`python -V`)?
3.6.8

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

```
uname_result(system='Linux', node='dca5b8fcc182', release='4.9.125-linuxkit', version='#1 SMP Fri Sep 7 08:20:28 UTC 2018', machine='x86_64', processor='')
```

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?

```
arlo==1.2.17
certifi==2018.11.29
chardet==3.0.4
idna==2.8
monotonic==1.5
PySocks==1.6.8
requests==2.21.0
six==1.12.0
sseclient==0.0.22
urllib3==1.24.1
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

n/a

### What did you do?

Ran a script which is fairly similar to `arlo-download.py`

### What did you expect to see?

The script should download new videos.

### What did you see instead?

`name 'requests' is not defined` is thrown.

It seems that the import for `requests` was removed [in this commit](https://github.com/jeffreydwalter/arlo/commit/5f9c6eaa73b1318c7f9601d1f8cc83e1bfb10dea#diff-05daa34ed4d7b1de26cf11277785f639L27) but usages of `requests` in `GetRecording` and `StreamRecording` were not refactored (e.g. https://github.com/jeffreydwalter/arlo/blob/master/arlo.py#L1376)

### Does this issue reproduce with the latest release?

Yes

**Comment by jeffreydwalter** [comment]
Good catch! Fixed in the latest release. Thanks!
