### ISSUE TITLE
Last Video

### ISSUE THREAD

**Issue by jsnoop315** [jeffreydwalter/arlo#11]
Is there a way to down load the most recent video from a specific camera?

**Comment by jeffreydwalter** [comment]
The videos are stored in Amazon AWS and not in your cameras. That being
said, yes, you can definitely do what you want with this library.

Take a look at the Arlo.py source code and the examples on the readme. You
should be able to figure it out from there. You basically have to call
GetLibrary() with a start and end date, which will return metadata about
all of the videos in that date range. Once you have that you should be able
to choose the video you want to download.
