### ISSUE TITLE
Update for arlo.com

### ISSUE THREAD

**Issue by kskenyon** [jeffreydwalter/arlo#113]
Do you plan to update this to use arlo.com instead of arlo.netgear.com?
The spin-off of Arlo from Netgear is essentially complete so arlo.netgear.com will probably go away soon.

Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

**Comment by jeffreydwalter** [comment]
Hello, I haven't really been keeping up with the Arlo happenings, but if they spin off and we need to change the domain name, I would of course do that (or accept a PR for it).

**Comment by kskenyon** [comment]
The new domain is my.arlo.com. It has already changed.

**Comment by jeffreydwalter** [comment]
Ok. The old domain is still working. If you want to update it I'll happily take a PR!

**Comment by natemiller82** [comment]
So....it looks like some people have found a way to integrate this with ST or Actiontiles, but I can't quite figure it out -- is there a way to use this API with webcore, or what's the best way of accomplishing this?

**Comment by jeffreydwalter** [comment]
@natemiller82 I have no idea what ST, Actiontiles, and webcore are, but it's just a library for making http requests, so I'm sure it's possible.

**Comment by jeffreydwalter** [comment]
Ok, so webcore is a website framework... How exactly are you wanting to integrate Arlo into your site? Do you want to show a live stream on your website? Control your camera from the website?

**Comment by natemiller82** [comment]
Sorry -- ST = Smartthings;  I saw in another forum that someone was supposedly able to use this API somehow to integrate with smartthings. 

Actiontiles essentially a nice looking client to manage smartthing devices.

**Comment by jeffreydwalter** [comment]
@m0urs thank you for knocking that out!
