### ISSUE TITLE
Talk with Arlo Station directly via LAN

### ISSUE THREAD

**Issue by cagnulein** [jeffreydwalter/arlo#124]
Is it possible to talk with an Arlo Station without going on internet? 
For example, i would like to arm/disarm my cameras from the rasp pi.

**Comment by jeffreydwalter** [comment]
No, the whole product is cloud-based. Messages are sent to Arlo servers and then distributed to the cameras. The cameras will only talk to their basestation, which will only talk to the Arlo servers.
