### ISSUE TITLE
Unable to subscribe to event using Arlo Q

### ISSUE THREAD

**Issue by fiberwings** [jeffreydwalter/arlo#128]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?

Python 3.5.3

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

uname_result(system='Linux', node='XXXX', release='4.14.71-v7+', version='#1145 SMP Fri Sep 21 15:38:35 BST 2018', machine='armv7l', processor='')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```
arlo==1.2.23
certifi==2019.6.16
chardet==3.0.4
cryptography==1.7.1
idna==2.8
jedi==0.10.2
keyring==10.1
keyrings.alt==1.3
monotonic==1.5
pyarlo==0.2.3
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
PySocks==1.7.0
python-apt==1.1.0b5
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.12.0
sseclient==0.0.24
sseclient-py==1.7
urllib3==1.25.3
virtualenv==15.1.0
```

### Which version of ffmpeg are you using (`ffmpeg -version`)?
```
Paste your output here
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

Arlo Q 

### What did you do?

I have an arlo Q so no basestation. So I have modified the example to subscribe to events removing the basestations filter like this.

basestations = arlo.GetDevices()

then when I run

arlo.SubscribeToMotionEvents(basestations[0], callback)

I get the following error:

Failed to subscribe to eventstream: __init__() got an unexpected keyword argument 'session'
Exception ignored in: <bound method EventStream.__del__ of <eventstream.EventStream object at 0x76255d90>>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/eventstream.py", line 48, in __del__
    self.Disconnect()
  File "/home/pi/.local/lib/python3.5/site-packages/eventstream.py", line 88, in Disconnect
    self.Unregister()
  File "/home/pi/.local/lib/python3.5/site-packages/eventstream.py", line 105, in Unregister
    if self.event_stream_thread != threading.current_thread():
AttributeError: 'EventStream' object has no attribute 'event_stream_thread'

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
Paste your ouptut here
```
I have used the 
 
### What did you expect to see?
```
Paste your ouptut here
```

### What did you see instead?
```
Paste your ouptut here
```

**Comment by jeffreydwalter** [comment]
You have two different server-side events libraries installed, which are incompatible.

Please uninstall `sseclient-py==1.7`.
