### ISSUE TITLE
Question - New Version Release

### ISSUE THREAD

**Issue by robweber** [jeffreydwalter/arlo#129]
Just wondering what your procedure is for when to release a new version? I've been looking to use the additions made in PR #126 but the version of the Arlo module available still doesn't include it. From what I can see [here](https://pypi.org/project/arlo/#history) version 1.2.23 was release in May of 2019. I can use the master Git repo for testing but would really like to depend on an actual release version for releasing any code into the wild. 

Is this something you do on a regular basis or just when you think there have been enough changes/additions? Thanks.

**Comment by jeffreydwalter** [comment]
Hey @robweber the general procedure is for me to push a new release to pypi, then create the release here in github. I generally make a new release anytime there are changes to the code that fix an issue,  but I guess I neglected to do that for the last pull request. I just did it now, so pypi should have the latest code. 

Thanks!
