### ISSUE TITLE
Can we use this API to start record instantly?

### ISSUE THREAD

**Issue by wangsheen100** [jeffreydwalter/arlo#13]
The arlo pro iphone app allows to record the live streaming. Does this API have same feature? In other words, how can I use this API to manually start the recording?

**Comment by jeffreydwalter** [comment]
I don't currently have my Arlo cameras hooked up, and I don't have Arlo Pro cameras, so I can't tell you for sure. That being said, my library simply wraps up the http calls that the UI makes, so if it's possible from the UI it should be possible with my library. I may or may not have added support for that function, as I didn't have a need for it when I wrote the library.

I will try to hook my cameras back up this weekend and see if I can work that out for you.

In the meantime, if you want to help out you can open your developer tools in your browser of choice (Chrome is best imho) and click through the feature you care about (recording in this case) in the UI and paste me the http urls and request bodies of those requests here.

Knowing which http requests your browser makes and what data it's sending will be a tremendous help. If you can get me those, I can definitely help you get going faster.

**Comment by huberda** [comment]
I had the same idea, because i wanted to take a video/photo from my home automation even when arlo is not detecting any motion - e.g. if a window sensor or local motion detector is triggered.
I just added three more methods to Arlo.py in my local setup which works fine fore me.
Maybe jeffrey can extend the next Arlo.py release with this functions. 
Greetings


`	def TakeSnapshot(self, parent_id, device_id, xcloud_id):
		self.GetStreamUrl(device_id, xcloud_id)
		return self.post('https://arlo.netgear.com/hmsweb/users/devices/takeSnapshot', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'TakeSnapshot',headers={"xcloudId":xcloud_id})

	def StartRecording(self, parent_id, device_id, xcloud_id):
		self.GetStreamUrl(device_id, xcloud_id)
		self.post('https://arlo.netgear.com/hmsweb/users/devices/startRecord', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'TakeSnapshot',headers={"xcloudId":xcloud_id})

	def StopRecording(self, parent_id, device_id, xcloud_id):
		return self.post('https://arlo.netgear.com/hmsweb/users/devices/stopRecord', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'TakeSnapshot',headers={"xcloudId":xcloud_id})`



Taking a Snapshot:
`from datetime import timedelta, date
from Arlo import Arlo

USERNAME = ‚XXXXX‘
PASSWORD = ‚XXXXX‘

try:
    arlo = Arlo(USERNAME, PASSWORD)
    basestation = [ device for device in arlo.GetDevices() if device['deviceType'] == 'basestation' ]
    arlo.TakeSnapshot(basestation[0]['deviceId'],'<Your Camera ID>', basestation[0]['xCloudId']);
except Exception as e:
    print (e)`


Taking a video of 4 seconds:
`import time
from datetime import timedelta, date
from Arlo import Arlo

USERNAME = ‚XXXXXX'
PASSWORD = 'XXXXXX'

try:
    arlo = Arlo(USERNAME, PASSWORD)
    basestation = [ device for device in arlo.GetDevices() if device['deviceType'] == 'basestation' ]
    arlo.StartRecording(basestation[0]['deviceId'],'<Your Camera ID>', basestation[0]['xCloudId']);
    time.sleep(4)
    arlo.StopRecording(basestation[0]['deviceId'],'<Your Camera ID>', basestation[0]['xCloudId']);
except Exception as e:
    print (e)`

**Comment by huberda** [comment]
I had the same idea, because i wanted to take a video/photo from my home automation even when arlo is not detecting any motion - e.g. if a window sensor or local motion detector is triggered.
I just added three more methods to Arlo.py in my local setup which works fine for me.
Maybe jeffrey can extend the next Arlo.py release with this functions. 
Greetings
```

	def TakeSnapshot(self, parent_id, device_id, xcloud_id):
		self.GetStreamUrl(device_id, xcloud_id)
		return self.post('https://arlo.netgear.com/hmsweb/users/devices/takeSnapshot', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'TakeSnapshot',headers={"xcloudId":xcloud_id})

	def StartRecording(self, parent_id, device_id, xcloud_id):
		self.GetStreamUrl(device_id, xcloud_id)
		return self.post('https://arlo.netgear.com/hmsweb/users/devices/startRecord', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'StartRecording',headers={"xcloudId":xcloud_id})

	def StopRecording(self, parent_id, device_id, xcloud_id):
		return self.post('https://arlo.netgear.com/hmsweb/users/devices/stopRecord', {'xcloudId':xcloud_id, 'parentId':parent_id, 'deviceId':device_id, 'olsonTimeZone':'Europe/Amsterdam'}, 'StopRecording',headers={"xcloudId":xcloud_id})

```


Taking a Snapshot:
```
from datetime import timedelta, date
from Arlo import Arlo

USERNAME = ‚XXXX‘
PASSWORD = 'XXXX'

try:
    arlo = Arlo(USERNAME, PASSWORD)
    basestation = [ device for device in arlo.GetDevices() if device['deviceType'] == 'basestation' ]
    arlo.TakeSnapshot(basestation[0]['deviceId‘],’<YOUR CAMERA ID>’, basestation[0]['xCloudId']);
except Exception as e:
    print (e)
```

Taking a Video of 4s:
```
import time
from datetime import timedelta, date
from Arlo import Arlo

USERNAME = ‚XXXXX‘
PASSWORD = 'XXXXX'

try:
    arlo = Arlo(USERNAME, PASSWORD)
    basestation = [ device for device in arlo.GetDevices() if device['deviceType'] == 'basestation' ]
    arlo.StartRecording(basestation[0]['deviceId'],'<YOUR CAMERA ID>', basestation[0]['xCloudId']);
    time.sleep(4)
    arlo.StopRecording(basestation[0]['deviceId‘],’<YOUR CAMERA ID>’, basestation[0]['xCloudId']);
except Exception as e:
    print (e)
```

**Comment by jeffreydwalter** [comment]
@huberda thanks for the code! I don't have my cameras setup, and don't have any pros, so it's impossible for me to test any of it.

I went ahead and added the three functions you suggested and also added your code examples! 

Thanks again!

**Comment by huberda** [comment]
Hi Jeff,

many thanks for adjusting the library!!! Your implementation is much cleaner - but i think there is one issue:

"# You can get the timezone from GetDevices()."
-> Thats right, but the "olsonTimeZone" is stored in cameras[0]['properties']['olsonTimeZone'], 
not in cameras[0]['olsonTimeZone']. I have no glue why olsonTimeZone is neede from the API.

Thats the output of my cameras[0]:
```
{u'deviceName': u'Arlo XXXX, u'mediaObjectCount': 0, u'lastImageUploaded': u'true', u'lastModified': 1502223371878L, u'presignedFullFrameSnapshotUrl': 
u'https://arlos3-prod-z1.s3.amazonaws.com/xxxxx', u'userId': u'HMXXXXXXXX', 
u'interfaceVersion': u'i000', u'properties': {u'olsonTimeZone': u'Europe/Amsterdam', u'hwVersion': u'VMC3030', u'modelId': ….
....
```

Best regards,
Daniel

**Comment by jeffreydwalter** [comment]
Hi Daniel,

Thanks for catching that! I was flying blind there since my Arlo cameras are in a box. 😃

**Comment by rayhou0710** [comment]
Hi Jeff and Daniel,

Thank you for adding such a function! I played with it and found that it may only support Arlo Pro. I am using an Arlo Go and it always showed "list index out of range" error after StartRecording is called. I guess it is because there is no base station for Arlo Go (LTE). 
Could you please give me some tips on how to figure out the web post or request for some specific purposes or where to start? I checked the "inspect" in chrome for the buttons in the UI. I guess I should look at the event listeners - especially "click"? However, I didn't see anything similar to the code. I really hope that I can also contribute to this project. Thanks!

**Comment by rayhou0710** [comment]
I am getting something like the follows for the start to record:

 ---  div class="cameras-control cameras-record" id="cameras_cameraRecord_XXXXXXX" ng-class="{'record-action' : isCameraRecording(camera)}" ng-disabled="!uiStates[camera.deviceId].play || uiStates[camera.deviceId].recordRequest || !canRecord(camera)" ng-click="uiStates[camera.deviceId].play &amp;&amp; toggleRecording(camera, $index)" role="button" disabled="disabled">div record-timer="" class="cameras-record-time ng-pristine ng-untouched ng-valid ng-hide" ng-model="uiStates[camera.deviceId].record" ng-show="uiStates[camera.deviceId].record &amp;&amp; canRecord(camera) &amp;&amp; !uiStates[camera.deviceId].recordRequest">00:00:03</div/div ----

**Comment by huberda** [comment]
Hi rayhou,

the snapshot/recording works also with the old arlo version, not only with Pro, but i never tested the Go version, because its not available in europe.
Maybe it will help if you could give us a overview about your arlo-devices array, so please post the ouput of something like:

devices = [ device for device in arlo.GetDevices() ]
print (devices);
...

Please remove your original ids, user,...
The html/flash object is not really helpful, maybe you could record the http-requests with firefox webdevloper-tools or something similar.

regards,
Daniel

**Comment by rayhou0710** [comment]
Hi Daniel @huberda ,

Thank you so much for the reply. I was on vacation in the last two weeks and had no access to PC. Sorry for the late response. The outputs of my Arlo Go device are as follows. Thanks again.

Ray

[{u'deviceName': u'Cam1', u'permissionsSchemaVer': u'i000', u'userId': u'xxxx-xxx-xxxxxxxx', u'mediaObjectCount': 54, u'owner': {u'lastName': u'xxx', u'firstName': u'xxx', u'ownerId': u'xxxx-xxx-xxxxxxxx'}, u'presignedLastImageUrl': u'https://arlolastimage-z2.s3.amazonaws.com/a155d6da_03c6_4d93_9559_f6fc96081267/9J85-300-9021299/xxxxxxxxxxx/lastImage.jpg?AWSAccessKeyId=xxxxxxxUAC4WFSD6C2A&Expires=1503975308&Signature=xxxxxxFdsUvilkAuBw0Ss7RmuKs%3D', u'permissionsVerison': u'002', u'permissionsFilePath': u'https://vzs3-prod-common.s3.amazonaws.com/static/resources/permissions/VML4030/VML4030_i000_permissions.json', u'state': u'provisioned', u'deviceType': u'camera', u'displayOrder': 3, u'uniqueId': u'9J85-300-9021299_xxxxxxxxxxxxxx', u'parentId': u'xxxxxxxxxxxxxx', u'presignedSnapshotUrl': u'https://arlos3-prod-z2.s3.amazonaws.com/a155d6da_03c6_4d93_9559_f6fc96081267/9J85-300-9021299/xxxxxxxxxxxxxx/snapshot.jpg?AWSAccessKeyId=xxxxxxxxxxxxxxFSD6C2A&Expires=1503975308&Signature=Uy1GRe%2BM0bDRbxf%2FE8xMvEw6A5A%3D', u'modelId': u'VML4030', u'userRole': u'OWNER', u'interfaceSchemaVer': u'4', u'connectivity': {u'signalStrength': u'5', u'rfBand': 850, u'networkMode': u'auto', u'roamingAllowed': False, u'msisdn': u'', u'networkName': u'AT&T', u'carrierFw': u'AT&T', u'fwVersion': u'ARLO.FX.0.0.0.24.AT.024', u'wwanIpAddr': u'xx.xxx.xxx.xxx', u'connected': True, u'iccid': u'xxxxxxxxxxxxxx', u'imei': u'xxxxxxxxxxxxxx', u'apn': u'broadband', u'roaming': False, u'type': u'lte', u'activeNetwork': u'hspa'}, u'deviceId': u'xxxxxxxxxxxxxx', u'properties': {u'olsonTimeZone': u'America/New_York', u'hwVersion': u'H5', u'modelId': u'VML4030'}, u'interfaceVersion': u'i000', u'lastImageUploaded': u'true', u'lastModified': 1503888908282, u'xCloudId': xxxxx-xxxx-xxx-xxxxxx', u'criticalBatteryState': False, u'presignedFullFrameSnapshotUrl': u'https://arlos3-prod-z2.s3.amazonaws.com/a155d6da_03c6_4d93_9559_f6fc96081267/9J85-300-9021299/xxxxxxxxxxxxxx/fullFrameSnapshot.jpg?AWSAccessKeyId=xxxxxxxxxxxxxx&Expires=1503975308&Signature=WS9FAF2CHWCqXW03l2z84wI13xQ%3D'}]

**Comment by jeffreydwalter** [comment]
Hi @rayhou0710,

You just need to do something like this:

```
devices = [ device for device in arlo.GetDevices() ]
cameras = [ device for device in devices if device['deviceType'] == 'camera' ]
arlo.StartRecording(cameras[0]['parentId'], cameras[0]['deviceId'], cameras[0]['xCloudId'], cameras[0]['properties']['olsonTimeZone']);
```

**Comment by jeffreydwalter** [comment]
@huberda can you do me a huge favor and please confirm whether or not the camera json for regular Arlo cameras (o.g. or Pro version) schema has the parentId, deviceId, xCloudId, and olsonTimeZone? I still haven't had a chance to hook my cameras back up...

If the camera schema actually always does have the parentId, then we can probably refactor the API and examples a bit to just pass in a camera object, like this:
```
devices = [ device for device in arlo.GetDevices() ]
cameras = [ device for device in devices if device['deviceType'] == 'camera' ]
arlo.StartRecording(cameras[0]); // Just have this method reference the fields in the camera json schema.
```
Which would also mean that we don't actually need the basestation info for most of the calls in this library.

I kind of like the idea of all of the methods that operate on a camera taking a camera object (and the ones that take a basestation taking a basestation object, etc.).

Thanks again!

**Comment by rayhou0710** [comment]
@jeffreydwalter 
Hi Jeff,

Thank you so much for helping out. I tried the code out - I called the StartRecording first then wait  for 2 mins and call StopRecording afterwards. The camera indeed started to record but the video is only 32 seconds each time and I got the error from the StopRecording call as follows:

('StopRecording failed', {u'data': {u'message': u'We are sorry, the streaming service is currently down.  Please try again.', u'reason': u'Media Server Unreachable', u'error': u'2602'}, u'success': False})

Any clue about the error?
Thanks!
Ray

**Comment by huberda** [comment]
@jeffreydwalter Yes, you are right! We have the parentId, deviceId and xCloudId in the camera json, so you can remove the basestation stuff and really clean up the functions.

@rayhou0710 Yes, you are right, too! I never tried recording videos bigger than 30s, cause the original arlos are running on normal batteries, so i am stopping the recodring after some seconds.
It seems that netgear is setting a timeout here, i will try to figure out more tomorrow.


```
try:
    arlo = Arlo(USERNAME, PASSWORD)
    devices = [ device for device in arlo.GetDevices() ]
    cameras = [ device for device in devices if device['deviceType'] == 'camera' ]
    print cameras[0];
```


`{u'deviceName': u'Arlo…’, u'mediaObjectCount': 0, u'lastImageUploaded': u'true', u'lastModified': 1503946651500L, u'presignedFullFrameSnapshotUrl': u'https://arlos3-prod-z1.s3.amazonaws.com......fullFrameSnapshot.jpg?AWSAccessKeyId=XXXXXX', u'userId': u'HXXXXX', u'interfaceVersion': u'i000', u'properties': {u'olsonTimeZone': u'Europe/Amsterdam', u'hwVersion': u'VMC3030', u'modelId': u'VMC3030'}, u'owner': {u'lastName': u'', u'firstName': u'', u'ownerId': u'HMEUXHK-'}, u'state': u'provisioned', u'deviceType': u'camera', u'deviceId': u’xxxxxxxxxxx’, u'uniqueId': u'HMEUXHK-XXX’, u'parentId': u’XXXXXXX’, u'interfaceSchemaVer': u'2', u'presignedSnapshotUrl': u'https://arlos3-prod-z1.s3.amazonaws.com/XXXXXXX/snapshot.jpg?AWSAccessKeyId=XXXXXXXX', u'modelId': u'VMC3030', u'presignedLastImageUrl': u'https://arlolastimage-z1.s3.amazonaws.com/XXXXXXX/lastImage.jpg?AWSAccessKeyId=XXXXXXX', u'xCloudId': u'XXXXXXXXX', u'displayOrder': 2, u'userRole': u'OWNER'}`

best regards, 
Daniel

**Comment by rayhou0710** [comment]
@huberda 
Thanks! Just FYI, currently I am using the official integration of Arlo and IFTTT to make the camera start to record instantly. The video duration in this case is 60 seconds maximum. If we manually let the camera capture video from the web UI, it can record for "infinite" long.

Best,
Ray

**Comment by jeffreydwalter** [comment]
Hi @huberda, just read this https://community.netgear.com/t5/Arlo/How-to-extend-recording-time-on-Arlo-wireless/m-p/1052809#M13405

Feeling a little silly for not catching this earlier, but you probably need to make sure your camera record time is set to 2 minutes. It's probably currently set to 30 seconds, if I had to guess.

**Comment by rayhou0710** [comment]
@jeffreydwalter 
Hi Jeff,
I received the notification email about your last comment but I am not sure why I cannot see it here in Github. 
Anyway, I played with the duration setting mentioned in the Arlo thread that you shared. It seems that it has nothing to do with the timeout of the StartRecoding function. Thanks!

Ray

**Comment by huberda** [comment]
@jeffreydwalter As rayhou mentioned, the time settings on the camera depends on the armed mode which could be used by Arlo. This setting is only used when the motion sensor is triggered and starts recodring.

@rayhou0710 You are right, via the webinterface its possible to record a video infinite. It seems that this 30seconds timeout comes from netgear.

Looking into the https-requests, i can see the the webapp sends the notify-request in a defined interval.
Maybe the general recording stops, if this request is not send anymore. I will try this evening to start a recodring and keep sending the Notify, maybe this works....
```

https://arlo.netgear.com/hmsweb/users/devices/notify/XXXXX
from	HMEUXHK-1XXXX
to	48EXXXXXXXXXX
action	set
resource	subscriptions/HMEUXHK-183-XXXXX
publishResponse	false
transId	web!a698a71b.b83aa!1504162691099
properties	Object
devices	[1]
0	XXXXXX
```

**Comment by rayhou0710** [comment]
@huberda 
Hi Daniel, you are right. I tried to send the notify-request every 10 seconds to record a 135 second long video. Sometimes it can record a video for 85 seconds but most of times it just return errors as follows:

('StartStream failed', {u'data': {u'message': u'The camera failed to connect. Try again.', u'reason': u'Your device failed to connect to media server, please try again.', u'error': u'2503'}, u'success': False})

or 

('StartRecording failed', {u'data': {u'message': u'The camera failed to connect. Try again.', u'reason': u'Your device failed to connect to media server, please try again.', u'error': u'2503'}, u'success': False})

Could you please help check what is the interval that Netgear uses？ Thank you!

Ray

**Comment by jeffreydwalter** [comment]
@huberda I just committed a big refactor of the API! All of the methods now take the "camera" or "basestation" json objects you get back from GetDevices(). I also made GetDevices() accept a filter parameter so you can do stuff like:
```
basestations = arlo.GetDevices("basestation")
#or
cameras = arlo.GetDevices("camera")
#or
all_devices = arlo.GetDevices()
```
You can then do stuff like:
```
arlo.GetRules(basestation[0])
arlo.Arm(basestation[0])
arlo.TakeSnapshot(camera[1])
```

Hopefully that makes things cleaner. :) I also tagged the old code as the 0.9 release in case people don't want to migrate to the new API.

**Comment by huberda** [comment]
Hi Jeff,

in was really busy the last weeks, but today i had a chance to have a look on your new Arlo.py release. It looks amazing and its much easier to handle now !
I just reworked all my scripts to the new version, looks good.

Thank you for still supporting this api so well, without having any cameras hooked up!

**Comment by jeffreydwalter** [comment]
Hey Daniel,

Thanks for all the feedback!

I'm glad to hear it's working well for you! 

Hopefully, I'll get some time soon to release the new version I've been working on. It'll be backwards compatible, but should be much more "python-esque".

Jeff
