### ISSUE TITLE
Check if video already exists locally before download - no delete from arlo after DL

### ISSUE THREAD

**Issue by HeliosVentilatoren** [jeffreydwalter/arlo#130]
No Bug but Feature Request:

I would like do have a local copy of the videos and keep them in Arlo library so I can still access them with the Arlo App.

Idea:
Check if filename already exists in local repository before downloading.
So only new files will be downloaded.

**Comment by jeffreydwalter** [comment]
That's out of the scope of this library. You can call `GetLibrary()` and check the video creation date to see if it's the same video as one you previously downloaded. Obviously, you would have to store that creation date (or name your file the creation date) so you could check it. Files are streams from an S3 bucket, they don't have names, just URLs and metadata.
