### ISSUE TITLE
Arming and disarming issue

### ISSUE THREAD

**Issue by rihani** [jeffreydwalter/arlo#131]
please could you help disarm/arm my base station
i have had this working, until i changed the stations, I did delete the old one from the list in the iOS app. so i only have 1 basestation. yet this script is not changing the state anymore.

**see response to the code:**

> [{u'deviceName': u'base', u'migrateActivityZone': False, u'userId': u'xxxxxx', u'mediaObjectCount': 0, u'owner': {u'lastName': u'me', u'firstName': u'saidnottohackme', u'ownerId': u'stilltrying!'}, u'displayOrder': 4, u'certAvailable': True, u'state': u'provisioned', u'deviceType': u'basestation', u'firmwareVersion': u'1.14.1.1_2913_78b189a', u'uniqueId': u':)', u'modelId': u'VMB4000', u'userRole': u'OWNER', u'cvrEnabled': False, u'interfaceSchemaVer': u'11', u'dateCreated': 1570343933774L, u'connectivity': {u'connected': True, u'type': u'ethernet', u'mepStatus': u'unknown'}, u'deviceId': u'4RE38706446768', u'properties': {u'olsonTimeZone': u'Australia/Sydney', u'hwVersion': u'VMB4000r3', u'modelId': u'VMB4000'}, u'interfaceVersion': u'i018', u'automationRevision': 12, u'lastModified': 1570447937968L, u'xCloudId': u'YCAPOOBH-1690-114-10090512944'}]

**code**:
```
from Arlo import Arlo
USERNAME = 'me@hotmail.com'
PASSWORD = 'donthackme'
basestations = arlo.GetDevices('basestation')
print basestations
arlo.Arm(basestations[0])
```

**Comment by jeffreydwalter** [comment]
You completely ignored the issue template. Please read the README and try again.
