### ISSUE TITLE
Cannot import arlo package

### ISSUE THREAD

**Issue by silicoon84** [jeffreydwalter/arlo#134]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?

Python 2.7.15+

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

 ('Linux', 'ip-172-31-31-209', '4.15.0-1051-aws', '#53-Ubuntu SMP Wed Sep 18 13:3           5:53 UTC 2019', 'x86_64', 'x86_64')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```
arlo==1.2.30
asn1crypto==0.24.0
certifi==2019.9.11
chardet==3.0.4
cryptography==2.1.4
enum34==1.1.6
idna==2.8
ipaddress==1.0.17
keyring==10.6.0
keyrings.alt==3.0
monotonic==1.5
pycrypto==2.6.1
pygobject==3.26.1
PySocks==1.7.1
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.12.0
sseclient==0.0.22
urllib3==1.25.6

```

### Which version of ffmpeg are you using (`ffmpeg -version`)?
```
Paste your output here
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

Arlo Pro 2

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
sudo apt install python
sudo apt install python-pip
pip install arlo
sudo apt install ffmpeg

created arlo.py from screenshot wiki https://github.com/jeffreydwalter/arlo/wiki/Taking-Full-Screen-Snapshots

python arlo.py


```

### What did you expect to see?
```
No errors!
```

### What did you see instead?
```
Traceback (most recent call last):
  File "arlo.py", line 1, in <module>
    from arlo import Arlo
  File "/home/ubuntu/arlo.py", line 1, in <module>
    from arlo import Arlo
ImportError: cannot import name Arlo
```

### Does this issue reproduce with the latest release?

Yes

**Comment by jeffreydwalter** [comment]
You can't name your script the same name as the package. Rename it to something other than `arlo.py`.
