### ISSUE TITLE
Download Video from Labrary

### ISSUE THREAD

**Issue by rayhou0710** [jeffreydwalter/arlo#14]
Hi Jeffrey,

I feel there is a bug in the exmple of downloading video that is shown in the Readme.md.
"f.buffer.write(chunk)" might be "f.write(chunk)" since the former one gives the error 'file' object has no attribute 'buffer' while the latter works well.

Thanks.
Ray

**Comment by jeffreydwalter** [comment]
Yes, someone updated all the code to be Python 3 compatible and changed that call to f.buffer.write. I don't have my Arlo cameras setup right now so couldn't test.

Thanks for reporting it, I'll fix it up ASAP.

**Comment by jeffreydwalter** [comment]
Okay, updated the example script and the README. Please let me know if your issue still persists.
