### ISSUE TITLE
DeleteRecording() & BatchDeleteRecordings() not working

### ISSUE THREAD

**Issue by badreamer** [jeffreydwalter/arlo#140]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
2.7.16
Also tested on 3.7.3

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Raspberry Pi 3 Model B+
uname_result(system='Linux', node='raspberrypi', release='4.19.75-v7+', machine='armv7l', processor='')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.2.32
asn1crypto==0.24.0
blinkpy==0.4.2
certifi==2019.11.28
chardet==3.0.4
configparser==3.5.0b2
cryptography==2.6.1
entrypoints==0.3
enum34==1.1.6
idna==2.8
ipaddress==1.0.17
keyring==17.1.1
keyrings.alt==3.1.1
monotonic==1.5
pycrypto==2.6.1
PyGObject==3.30.4
PySocks==1.7.1
pyxdg==0.25
requests==2.22.0
RPi.GPIO==0.7.0
SecretStorage==2.3.1
six==1.12.0
sseclient==0.0.22
urllib3==1.25.7

### Which version of ffmpeg are you using (`ffmpeg -version`)?

No ffmpeg installed

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

Arlo Pro & Arlo Pro 2

### What did you do?
If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```arlo.DeleteRecording(recording)```
```arlo.BatchDeleteRecordings(library)```

### What did you expect to see?
For: ```arlo.DeleteRecording(recording)```
Expect a single video to be deleted from the library
For: ```arlo.BatchDeleteRecordings(library)```
Expect all videos to be deleted from library

### What did you see instead?
For: ```arlo.DeleteRecording(recording)```
The video is not deleted
For: ```arlo.BatchDeleteRecordings(library)```
Exception thrown: 
```global name 'recording_metadata' is not defined```

### Does this issue reproduce with the latest release?
Yes

**Comment by badreamer** [comment]
Deleting 
```if(global_metadata)``` in ```arlo.py``` allows me to batch delete the videos (which works). Not sure why ```DeleteRecording(recording)``` is not working though.

**Comment by jeffreydwalter** [comment]
@badreamer there's no `global_metadata` in arlo.py (or any of the code for that matter). Please provide a full working example of your issue.

**Comment by jeffreydwalter** [comment]
Ok, I see you meant `recording_metadata`. I fixed that in the latest release. Without a full working example of your problem with `DeleteRecording()` I won't be able to help you.
