### ISSUE TITLE
Catch the motion event type category

### ISSUE THREAD

**Issue by gubbfett** [jeffreydwalter/arlo#143]
Great wrapper!
However, im not really sure how i should get the category for the motion event.
I need to check if it's "Person", "Animal", "Movement" etc. 

I can get this info when im using the API and calls for https://arlo.netgear.com/hmsweb/users/library, here the attribute is called "objCategory". When i get an motion alert in my phone it tells me what kind of movement it was, so it should be fully doable...?

Is it possible to get more data about the event?

**Comment by jeffreydwalter** [comment]
Hello, I have older Arlo cameras and am too cheap to pay for the AI stuff, so I'm not really sure how all of that works. If you just want to capture events and react to them, checkout out this example: https://github.com/jeffreydwalter/arlo/wiki/Subscribe-to-Motion-Events

**Comment by gubbfett** [comment]
Well yea, i have the old (?) as well (Arlo Pro) but i pay for the AI. Actually it's quite nice, it recognizes objects better than expected. And i my case i'd really like it since my project is to light up som lights when the camera sees a car or person (if it's dark enough). 
I am using the code in the link but non of the objects (event/basestation/arlo) contains information of what kind of object it sees. When i get data from the library i have an attribute called objCategory that contains "Animal", "person" etc (i was asking on /hmsweb/users/library, not with this wrapper), but it seems that i can't get it when I 'm using the motion events in this wrapper. Maybe because this information does not exists here or because since you do not have that feature it's not tested in this project. :) 

When i recieve a push notification on my phone (probably the same rest endpoint as subscribe?) i get a notification about what object it is directly, so i guess this information can be provided.

Anyway, i'll try to figure this out by debugging and testing on your lib, i was just hoping you may had some good inputs since your experience with this API is way better than mine. :)

**Comment by jeffreydwalter** [comment]
@gubbfett the subscribe endpoint is not related to push notifications. The whole Arlo platform is built around the event stream protocol. This protocol is basically a unidirectional channel (http socket). The Arlo web/mobile app makes http requests with JSON data to `/notify`. The responses to those requests are returned asynchronously via the event stream. So, the web/mobile apps "subscribe" to those events via the `/subscribe` endpoint. The web/mobile app UI uses those asynchronous events to update state in the UI. e.g., a camera detects motion, an event is sent on the stream, and the UI reads it and shows a little motion detected icon.

The Arlo platform will generate events when motion is detected, a video/snapshot is initiated/completed, etc. I assume you would want to listen for those events (there is a "new video ready in your library" event). When you receive that event, you'd probably want to make a request to the library to get your video metadata via `GetLibrary()`.

Obviously, I haven't been keeping up with the newer features Arlo has been adding, so all of what I said is just conjecture.

**Comment by gubbfett** [comment]
@jeffreydwalter thanks for great input. Well, that was my first approach, to scan the library. The library, however, does not seem to be updated until the recording is done. This triggers too late, unfortunately. Since i wanna turn on lights when a car or person arrive it will not turn on lights until the person or car is still and the recording stops. That is, it will turn on the lights when the person or car leaves the area i wanna light up to help the person. ;) 

Since the mobile app gives me info about object type in the push notice, i guess there is a way of getting the corresponding "objCategeory" on the motion event, instead of metadata by GetLibrary (since it's not yet in the library). 
EDIT: With this I mean that the API actually knows what typ of movement is going on, i don't think the push notification are generated elsewhere or from something else. And since it can deliver the type in the push notification, there must be a way of getting it. Just trying to figure out how. :) 

The knowledge you have, it this by try and error or have you found any better documentation of the Arlo REST API? (I have found none).
