### ISSUE TITLE
How can I get a link to the RTSP stream?

### ISSUE THREAD

**Issue by earlywaff** [jeffreydwalter/arlo#147]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
3.7

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

Rasberry Pi 4 
### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
```
arandr==0.1.9
arlo==1.2.33
asn1crypto==0.24.0
automationhat==0.2.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2019.9.11
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==2.6.1
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
gpiozero==1.5.1
gyp==0.1
idna==2.8
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
monotonic==1.5
mote==0.0.4
motephat==0.0.2
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.5
pigpio==1.44
Pillow==5.4.1
pycairo==1.16.2
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyserial==3.4
PySocks==1.7.1
pyxdg==0.25
rainbowhat==0.1.0
requests==2.22.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.7.0
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.4
sseclient==0.0.22
touchphat==0.0.1
twython==3.7.0
unicornhathd==0.0.4
urllib3==1.25.6
Werkzeug==0.14.1

Paste your ouptut here
```

### Which version of ffmpeg are you using (`ffmpeg -version`)?
```
-
Paste your output here
```

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro 2 

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
Paste your ouptut here
```

### What did you expect to see?
```
Paste your ouptut here
```

### What did you see instead?
```
Paste your ouptut here
```

### Does this issue reproduce with the latest release?

Good afternoon! Can you tell me in three words how to get a link to RTSP?
I do not really understand programming. Yesterday I installed Python 3, installed seeclient 0.0.22, and installed TSL.
I went in and found the Arlo files in the folder and tried to run the script through python, but on the very first line where arlo - arlo is written, I got an error .. Tell me, maybe I'm doing something wrong?

**Comment by earlywaff** [comment]
I figured out and got the link. Please tell me, when you restart rasberry pi, you need to get the link again?

**Comment by jeffreydwalter** [comment]
You have to get the link everytime you want to stream the video.
