### ISSUE TITLE
Install problems 

### ISSUE THREAD

**Issue by nthbooth** [jeffreydwalter/arlo#15]
When running Make against the repository clone I get the following message:
Collecting json (from -r requirements.txt (line 1))
  Using cached json-99.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uKjNmz/json/setup.py", line 2, in <module>
        raise RuntimeError("Package 'json' must not be downloaded from pypi")
    RuntimeError: Package 'json' must not be downloaded from pypi

I have been trying to track down the module but have not yet been able to if there is anyone else who has come across this issue and located the module it would be great to know.

Platform:
Ubuntu xenial - Linux pan 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

I have tried this with 
Python 2.7.12  and Python 3.5.2 both version of pip can't locate the module json (well they can but get the stub which does not help identify where I can install it from.  The Stubs setup.py just inclusdes "raise RuntimeError("Package 'json' must not be downloaded from pypi")"

Any help would be appreciated. 

Nick

**Comment by jeffreydwalter** [comment]
Hey @bg214884, I had the json package in my requirements.txt file which was not needed. I removed it so you should be good to go now.

Please let me know if that fixed your problem.

Thanks!
Jeff

**Comment by jeffreydwalter** [comment]
@bg214884 I'm closing this since I haven't heard back from you. The issue should be fixed, but if you're still having issues please open a new issue. Thanks!
