### ISSUE TITLE
Arlo video doorbell

### ISSUE THREAD

**Issue by romaindebrito** [jeffreydwalter/arlo#156]
Python version 3.6
Plateform : MacOS and Linux
Package fun : minimum python + arlo
I have an Arlo video Doorbell

I Want to Connect to the stream url like describe in readme but i don’t have an arlo basestation ! Video doorbell is a standalone system direct with arlo app !

This library could be adapt to implement this case ?

I can work in this case with explanation and collaboration !

Thanks for your vélo

**Comment by giejay** [comment]
I think you can just use:

url = arlo.StartStream(cameras[0], cameras[0])

**Comment by romaindebrito** [comment]
Yes it's works.
Thanks very much
Regards
