### ISSUE TITLE
Does Arlo only support output of RTSPS, or RTSP as well?

### ISSUE THREAD

**Issue by roflware** [jeffreydwalter/arlo#157]
I removed the irrelevant questions below. My question for the Arlo Pro is if RTSP can be forced over RTSPS. The reason for this is that I would like to use the Arlo Pro with my Synology.

Thanks!

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?

Arlo Pro

**Comment by BitVenturesUSA** [comment]
The Arlo cameras are locked down and do not support any open protocols like RTSP or ONVIF.
