### ISSUE TITLE
How To Check If Camera Is On Or Off?

### ISSUE THREAD

**Issue by prakash-patel** [jeffreydwalter/arlo#158]
By calling Notify endpoint i can turn on and off camera. Is that any endpoint i can call for device and they tells me if camera is on or off?

**Comment by sniggum42** [comment]
I too am struggling to find a way to validate the status of a camera. What is the best way to return the on/off status of a device ?

**Comment by jeffreydwalter** [comment]
Try `GetCameraState`.

**Comment by sniggum42** [comment]
Using GetCameraState I can see the 'privacyActive' attribute change when I turn one of the cameras on or off. 'False' for on, 'True' for off. Seems a strange attribute to report on
