### ISSUE TITLE
StartRecording issue

### ISSUE THREAD

**Issue by timfv** [jeffreydwalter/arlo#18]
Why is the StartRecording method limited to 31 seconds of recording time?

**Comment by jeffreydwalter** [comment]
Still working on figuring that out. My guess is that the browser is sending a "keep-alive" message to the basestation, which my API is not doing.

**Comment by rayhou0710** [comment]
Hi Jeffrey,

May I ask if you have any new thought on how to solve this issue? Thanks!

Ray

**Comment by jeffreydwalter** [comment]
Hi Ray,

Sorry, but I have not had much time lately. I will take a look at it next week and let you know.

Jeff

**Comment by rayhou0710** [comment]
Thank you! Please let me know if there is anything I could help.

**Comment by rayhou0710** [comment]
Hi Jeff,

Any luck on this? 

Ray

**Comment by jeffreydwalter** [comment]
Hey @rayhou0710 I'm sorry I haven't really had time to dig into this. If you have the time you could help by using the `HandleEvents(self, basestation, callback, timeout=None)` method to monitor what events you get when you start a stream.

The code will probably look something like this:
```
import json

def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

arlo = Arlo(USERNAME, PASSWORD)

basestations = arlo.GetDevices('basestation')
cameras = arlo.GetDevices('camera')

def callback(arlo, basestation, event):
    pp(event)
    # Here you will have access to self, basestation_id, xcloud_id, and the event schema.

arlo.StartRecording(cameras[0])
arlo.HandleEvents(basestations[0], callback)
```

Run that and see what events you get. We really need to inspect the traffic flowing to the server when recording. I suspect there is some sort of keep-alive being sent.

**Comment by jeffreydwalter** [comment]
Eh, just ran that script... Doesn't seem to produce any incoming events. We really need to inspect the traffic flowing to their servers when you start a recording from the UI or app.

**Comment by jeffreydwalter** [comment]
Oh, spoke too soon! 😃 

```
In callback
{
    "createdDate": "20171116", 
    "deviceId": "XXXXXXXXXXXX", 
    "mediaObjectCount": 1, 
    "ownerId": "336-XXXXXXX", 
    "presignedContentUrl": null, 
    "presignedLastImageUrl": "https://arlolastimage-z2.s3.amazonaws.com/a1289c23_7476_4b79_ab4f_0fadd9d785ab/XXX-XXXXXXX/XXXXXXXXXXXX/lastImage.jpg?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1510944669&Signature=S%XXXXXXXXXXXXXXXXXXXXX%3D", 
    "presignedThumbnailUrl": null, 
    "resource": "mediaUploadNotification", 
    "uniqueId": "336-4764296_XXXXXXXXXXXX"
}
In callback
{
    "action": "is", 
    "from": "XXXXXXXXXXXX", 
    "properties": {
        "activityState": "idle"
    }, 
    "resource": "cameras/XXXXXXXXXXXX", 
    "to": "mediaserver:336-XXXXXXX", 
    "transId": "Player did not join in 30000 ms for streamName:XXXXXXXXXXXX_XXXXXXXXXXXX"
}
In callback
{
    "action": "is", 
    "from": "XXXXXXXXXXXX", 
    "properties": {
        "activityState": "idle", 
        "dateStarted": -970219510
    }, 
    "resource": "cameras/XXXXXXXXXXXX", 
    "transId": "XXXXXXXXXXXX!29886116!XXXXXXXXXXXX"
}
In callback
{
    "createdDate": "20171116", 
    "deviceId": "XXXXXXXXXXXX", 
    "mediaObjectCount": 1, 
    "ownerId": "336-XXXXXXX", 
    "presignedContentUrl": "https://arlos3-prod-z2.s3.amazonaws.com/a1289c23_7476_4b79_ab4f_0fadd9d785ab/XXX-XXXXXXX/XXXXXXXXXXXX/recordings/1510858238603.mp4?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1510944670&Signature=78fm4JJ7%2FM%XXXXXXXXXXXX%2FU%3D", 
    "presignedLastImageUrl": "https://arlos3-prod-z2.s3.amazonaws.com/a1289c23_7476_4b79_ab4f_0fadd9d785ab/XXX-XXXXXXX/XXXXXXXXXXXXX/recordings/1510858238603_thumb.jpg?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1510944670&Signature=XXXXXXXXXXXXXXXXXXXXX%3D", 
    "presignedThumbnailUrl": "https://arlos3-prod-z2.s3.amazonaws.com/a1289c23_7476_4b79_ab4f_0fadd9d785ab/XXX-XXXXXXX/XXXXXXXXXXXXX/recordings/1510858238603_thumb.jpg?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1510944670&Signature=XXXXXXXXXXXXXXXXXXXXX%3D", 
    "resource": "mediaUploadNotification", 
    "uniqueId": "336-4764296_XXXXXXXXXXXX"
}
```

**Comment by jeffreydwalter** [comment]
@rayhou0710 this message 
```
"to": "mediaserver:336-XXXXXXX", 
"transId": "Player did not join in 30000 ms for streamName:XXXXXXXXXXXX_XXXXXXXXXXXX"
```
makes me think it's waiting for the rtmps flash player to connect, and since it doesn't it's timing out. If that's the case, we probably won't be able to make that work until someone cracks the inner workings of the rtmps security model. :/

**Comment by rayhou0710** [comment]
Hi Jeff,
Thank you for looking into this! 
Ray

**Comment by jeffreydwalter** [comment]
@rayhou0710 @timfv,  @deanmcguire added some code here https://github.com/jeffreydwalter/arlo/commit/89685f135d3122b1886bbf7d4767b9f5e943963b that pings the event stream every 30 seconds, which should fix the issue with StartRecording.

Please let me know if things are working any better after pulling the latest code.

**Comment by jeffreydwalter** [comment]
After some testing, looks like StartRecording is still missing something. :/ Will spend some time debugging tonight.

**Comment by deanmcguire** [comment]
Think I potentially know why the recordings are stopping at ~30sec. 

When you call startStream, if you don’t connect to the stream within 30sec it will tear the url down and return a 404. 

So I’m assuming when you call startRecord, it’s recording that stream for the 30sec it’s alive. Best way to resolve is to actually consume the stream I would think (via ffmpeg or something similar) which can keep it open indefinitely, but that may defeat the purpose of what you’re trying to achieve.

**Comment by jeffreydwalter** [comment]
That makes sense, since that's basically what the UI is doing. It starts recording while streaming. Kind of unfortunate that they Netgear guys wrote such a shitty interface... :/

**Comment by jeffreydwalter** [comment]
@rayhou0710 I think @deanmcguire is right. You will probably have to open the rtsps stream in the background with something like ffmpeg or OpenCV if you want the record feature to work. I threw together a really quick and dirty example of video streaming in the Wiki https://github.com/jeffreydwalter/arlo/wiki/Streaming-Video

Since you probably have to stream the video locally anyway, it might not be worth using the record feature. Instead, you mine as well just pull the rpsts stream locally. :) I guess it will depend on your use case.

**Comment by jeffreydwalter** [comment]
Closing due to age and the fact that this has been figured out. For anyone that finds this in the future, you have to start reading the stream from the url that is returned by StartRecording(). You can do that with ffmpeg or OpenCV. Of course, if you're already streaming the video you could just write it to a file. :)
