### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by jaajee** [jeffreydwalter/arlo#19]
Hello Jeff,
First of all sorry for posting this as an issue because I am new to GitHub and don't know how to send PM or Email to you. I want to know more about the project because I'm planning to buy Arlo (used from my friend) but I do not want to send the feed to Arlo server but want to save on my server instead. I was searching on google and came across your project. Your Wiki is not completed so I couldn't understand the whole project. Does it help to send feed to given server location? If I clone it on Raspberry Pi how I am going to connect it to Base-station or How I am going to access it from Raspberry Pi? I know you are already busy working on this and other projects but I'm really interested in this one so could you please take some time and explain it little more. my email is digbigg@gmail.com. I will really appreciate your help. Thanks in advance.

**Comment by jeffreydwalter** [comment]
@jaajee the cameras will not work without the Arlo servers, as they are cloud-based. 

This library is basically a wrapper around the Arlo API used by their web app (and mobile app).
This library lets you do almost everything you can do from the web app UI.

It works by connecting to the arlo webserver through their API. With this library, you can download/delete videos (which are stored in aws), start/stop recordings, take snapshots, arm/disarm cameras, manage camera/basestation settings, manage account information, etc. Basically, anything you can do from the web app UI.

If you clone this library to your raspberry pi, you will need to write some code to make the library do what you need. Your raspberry pi will need to be able to connect to the internet.

You should take a look at the *Code Examples* in the [wiki](https://github.com/jeffreydwalter/arlo/wiki).

**Comment by jeffreydwalter** [comment]
Closing this due to lack of response.
