### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by seroper** [jeffreydwalter/arlo#20]
Hi,

I've followed your install instructions, but it won't install on my pi, latest raspbian.  Below is the error I get, from make.  Any help much appreciated.

Thanks

> pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): sseclient in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): monotonic in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from sseclient->-r requirements.txt (line 2))
Cleaning up...
test:
make: test:: Command not found
Makefile:2: recipe for target 'init' failed
make: *** [init] Error 127

>

**Comment by jeffreydwalter** [comment]
@seroper, sorry about that. It appears the wrong version of the MakeFile got checked in. I fixed the issue and tested on my pi and it installed just fine.
