### ISSUE TITLE
Turn siren on/off

### ISSUE THREAD

**Issue by lundpetersen** [jeffreydwalter/arlo#21]
Hi - have you been experimenting with turning the siren in the pro base on and off?
I would like to be able to integrate the siren into my home automation system.

**Comment by lundpetersen** [comment]
@jeffreydwalter - I actually figured it out and added a few lines to Arlo.py - I now basically nothing about GitHub - how do I send the lines to you if you are interested?

**Comment by jeffreydwalter** [comment]
@lundpetersen thanks for offering to add these functions! The best way to contribute is to "fork" my repository (you just click the "Fork" button at the top right of my repo landing page).
Once you have a fork, you just clone it locally, modify the files, then add and commit them. Once you have committed the changes to your fork, you will need to create a Pull Request, to merge the changes from your fork to my repo.

1. Fork
2. Make changes and save them to your forked repo:
```
# From the command-line:
$ git commit -a -m "Adding functions to toggle alarm siren"
$ git push
```
3. Create a Pull Request to merge the changes from your fork to my repo, from the browser.
4. I'll do a code review and merge the changes.

**Comment by jeffreydwalter** [comment]
Alternatively, you can just past your code here and I'll make the changes for you. :)

**Comment by jeffreydwalter** [comment]
@lundpetersen thank you for your contribution! The code looks great! :)
