### ISSUE TITLE
can't complete setup.py (error on pyarlo)

### ISSUE THREAD

**Issue by MechEng70** [jeffreydwalter/arlo#25]
### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
**('Linux', 'MediaServer', '4.11.5-041105-generic', '#201706141137 SMP Wed Jun 14 15:39:07 UTC 2017', 'x86_64', 'x86_64')**

### Which Arlo hardware do you have (camera types, basestation model, etc.)?
**Basic Arlo**
### What did you do?
cloned 
installed dependencies
/opt/arlo$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pyarlo.egg-info/requires.txt
writing pyarlo.egg-info/PKG-INFO
writing top-level names to pyarlo.egg-info/top_level.txt
writing dependency_links to pyarlo.egg-info/dependency_links.txt
**error: package directory 'pyarlo' does not exist**

Not sure what I am doing wrong?

**Comment by jeffreydwalter** [comment]
@MechEng70 the problem is related to the setup.py script. I'm not super familiar with python packages and was fumbling around with it. I tested it locally and it didn't complain so I figured I had it working. Fix is on it's way.

**Comment by jeffreydwalter** [comment]
Fixed here https://github.com/jeffreydwalter/arlo/commit/91f7449a76aa5b4ba5d5e5fe665ee6e85dc3c905

Please let me know how it works for you.

**Comment by MechEng70** [comment]
Looks like setup is working... however does not seem to install the modules... see section below.

**warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install**

**bdist.linux-x86_64** exists... 

```
/opt/arlo$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating arlo.egg-info
writing requirements to arlo.egg-info/requires.txt
writing arlo.egg-info/PKG-INFO
writing top-level names to arlo.egg-info/top_level.txt
writing dependency_links to arlo.egg-info/dependency_links.txt
writing manifest file 'arlo.egg-info/SOURCES.txt'
reading manifest file 'arlo.egg-info/SOURCES.txt'
writing manifest file 'arlo.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying arlo.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying arlo.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying arlo.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying arlo.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying arlo.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/arlo-1.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing arlo-1.0.0-py2.7.egg
Copying arlo-1.0.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding arlo 1.0.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/arlo-1.0.0-py2.7.egg
Processing dependencies for arlo==1.0.0
Searching for sseclient==0.0.18
Best match: sseclient 0.0.18
Adding sseclient 0.0.18 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for monotonic==1.4
Best match: monotonic 1.4
Adding monotonic 1.4 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for certifi==2017.11.5
Best match: certifi 2017.11.5
Adding certifi 2017.11.5 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for arlo==1.0.0

```

**Comment by jeffreydwalter** [comment]
Sounds like you might be running setup.py from a folder other than the one it's in. see https://stackoverflow.com/questions/14865990/python-module-wont-install

**Comment by jeffreydwalter** [comment]
Actually, seems like from your output that it did install all of the dependencies. Can you run `pip freeze` or `pip3 freeze` and paste the output here?

**Comment by MechEng70** [comment]
pip freeze

apsw==3.8.11.1.post1
arlo==1.0.0
asn1crypto==0.23.0
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
Cheetah==2.4.4
CherryPy==3.5.0
configobj==5.0.6
cryptography==2.1.4
cssselect==0.9.1
cssutils==1.0
dnspython==1.12.0
enum34==1.1.6
feedparser==5.1.3
html5lib==0.999
idna==2.6
ipaddress==1.0.18
lxml==3.5.0
Markdown==2.6.6
mechanize==0.2.5
mercurial==3.7.3
monotonic==1.4
netifaces==0.10.4
Pillow==3.1.2
psutil==3.4.2
pyasn1==0.1.9
pycparser==2.18
pycrypto==2.6.1
Pygments==2.1
pygobject==3.20.0
pyOpenSSL==0.15.1
pyparsing==2.0.3
python-dateutil==2.4.2
PyYAML==3.11
repoze.lru==0.6
requests==2.18.4
Routes==2.2
sabyenc==3.3.1
six==1.11.0
sseclient==0.0.18
urllib3==1.22
uTidylib==0.2
WebOb==1.5.1
yenc==0.4.0

**Comment by jeffreydwalter** [comment]
Thanks for that. Based on what you have installed, it looks like the setup did install all of the required libraries. You have monotonic, sseclient, requests, and their dependencies.

**Comment by MechEng70** [comment]
noticed that I can only run the `arlo-armdisarm.py` from the Arlo root directory.  does not seem to be adding the `Arlo.py` to the path.  
Copied the script to create an `arlo-arm.py` and `arlo-disarm.py`.  placed them in the /opt/arlo directory.  ran them with `python arlo-arm.py` and it hangs up.  put some print() statements in the py script and determined that the `arlo.Arm(basestations[0])` is hanging up.

thoughts on what to do?
print(arlo) does provide feedback: `<Arlo.Arlo object at 0x7fc4e383fcd0>`.  then have to ctrl-C to stop the script...

**Comment by jeffreydwalter** [comment]
Without seeing your code it's hard to say. Please include your code sans your credentials.

**Comment by MechEng70** [comment]
```
from Arlo import Arlo

USERNAME = 
PASSWORD = 

try:
        # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
        # Subsequent successful calls to login will update the oAuth token.
        arlo = Arlo(USERNAME, PASSWORD)
        # At this point you're logged into Arlo.
        # Get the list of devices and filter on device type to only get the basestation.
        # This will return an array which includes all of the basestation's associated metadata.
        basestations = arlo.GetDevices('basestation')
        print(arlo)
        # Arm Arlo.
        arlo.Arm(basestations[0])
        # Or
        # Disarm Arlo.
        # arlo.Disarm(basestations[0])
except Exception as e:
    print(e)
```

Output:
`<Arlo.Arlo object at 0x7fa233adacd0>`

**Comment by jeffreydwalter** [comment]
What does `print(basestations)` output?

**Comment by MechEng70** [comment]
[{u'deviceName': u'MyArlo', u'properties': {u'olsonTimeZone': u'America/New_York', u'hwVersion': u'VMB3010r2', u'modelId': u'VMB3010'}, u'mediaObjectCount': 0, u'lastModified': 1512941224192, u'userId': u'336-1111854', u'displayOrder': 2, u'dateCreated': 1481421743289, u'state': u'provisioned', u'deviceType': u'basestation', u'deviceId': u'48946879AA89D', u'uniqueId': u'336-1111954_48946879AA19D', u'interfaceVersion': u'i001', u'owner': {u'lastName': u'XXXXXX', u'firstName': u'XXXXX', u'ownerId': u'336-1111954'}, u'interfaceSchemaVer': u'2', u'modelId': u'VMB3010', u'xCloudId': u'C5CMDF2-1005-336-5377971', u'firmwareVersion': u'1.9.4.0_15548', u'userRole': u'OWNER'}]

**Comment by jeffreydwalter** [comment]
@MechEng70 I _finally_ got time to make a proper pip package. Sorry it took me a while.

You should be able to install with ```pip install arlo```
```
$ sudo pip install arlo
Collecting arlo
  Downloading arlo-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: sseclient in /usr/local/lib/python2.7/dist-packages (from arlo)
Requirement already satisfied: PySocks in /usr/local/lib/python2.7/dist-packages (from arlo)
Requirement already satisfied: monotonic in /usr/local/lib/python2.7/dist-packages (from arlo)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from arlo)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from sseclient->arlo)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->arlo)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->arlo)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->arlo)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->arlo)
Installing collected packages: arlo
Successfully installed arlo-1.0.0
```
The package is here: https://pypi.python.org/pypi/arlo/1.0.0
