### ISSUE TITLE
Issues downloading the files

### ISSUE THREAD

**Issue by raspydev** [jeffreydwalter/arlo#27]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
2.7.10

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Darwin', 'zzz-MacBook-Pro.local', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64', 'x86_64', 'i386')

### Which Python packages do you have installed (`pip freeze` or `pip3 freeze`)?
pip freeze

### Which Arlo hardware do you have (camera types, basestation model, etc.)?
Arlo Pro, VMS3530

### What did you do?
I got the latest library code  from github. I was able to build everything properly. I used the sample code and replaced with my credentials. I was trying to download my video files. I got the following error. I tried varying the dates but similar errors occurred.  From the error looks like the file names formed within the sample code is not valid.

[Errno 2] No such file or directory: u'videos/2017-11-27 23-32-20 GWFVE-336-8951756_4N716A734E38D.mp4'

If possible, provide a recipe for reproducing the error.
A complete runnable program is good. (don't include your user/password or any sensitive info)
- Same sample code

### What did you expect to see?
all video files are downloaded

### What did you see instead?
[Errno 2] No such file or directory: u'videos/2017-11-27 23-32-20 GWFVE-336-8951756_4N716A734E38D.mp4'

**Comment by jeffreydwalter** [comment]
The videos directory doesn't exist. The script attempts to create it, but it seems like it did not. Did you run the script with proper permissions for it to create that folder?

**Comment by raspydev** [comment]
Thanks for the quick response. It works now, I manually created the "videos" folder and reran the script, it is downloading the files.
