### ISSUE TITLE
Downloaded files will not play on Win32 - Workaround for Win32

### ISSUE THREAD

**Issue by ghost** [jeffreydwalter/arlo#34]
### What version of Python are you using (`python -V`)?
Python 2.7.12

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
python -c "import platform; print(platform.uname());"
('Windows', 'AK_i7', '7', '6.1.7601', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
E:\arlo\examples>pip freeze
arlo==1.0.0
bottle==0.12.9
build==1.0.2
click==5.1
colorama==0.3.7
docutils==0.12
Kivy==1.9.0
Kivy-Garden==0.1.4
lockfile==0.12.2
monotonic==1.4
mysql-connector-python==2.1.2
platformio==2.11.2
pycairo==1.8.10
pyglet==1.2.4
Pygments==2.0.2
pygobject==2.28.3
pygtk==2.24.0
pyserial==3.1.1
requests==2.11.0
six==1.11.0
sseclient==0.0.18
UNKNOWN==0.0.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Basic Arlo Camera

### What did you do?
Downloaded files would not play.

For those that may have a similar issue using win32 (specifically Windows 7 Pro, but probably all windows OS version Python 2.7 will run on), here is a simple workaround.  Credits to: https://stackoverflow.com/questions/38404827/avoid-writing-carriage-return-when-writing-line-feed-with-python [UBICA]

Sorry, I'm not familiar with Python -- I usually use perl for scripting, so this is probably not an optimal solution.

Changed line 36 "with open(videopath + '/' + videofilename, 'w') as f:"
to:  "with open(videopath + '/' + videofilename, 'wb') as f:"

Apparently opening in the binary mode forces windows to interpret data literally -- does not replace LF wioth CRLF.

### What did you expect to see?
LF only was expected in downloaded file

### What did you see instead?
Found CRLF (classic windoze vs xNIX issue)

### Does this issue reproduce with the latest release?
Assuming this is generic to any win32 OS and current example scripts.

Downloaded files play as well as files saved from the ARLO App.  Thanks so much for making ARLO useful for me!  Not having an archive > 7 days caused loss of useful data (people stealing hose in front yard - then oddly, replacing it!).  Now I can archive videos!

**Comment by jeffreydwalter** [comment]
Thanks for reporting this! Fixed.

**Comment by jimletts** [comment]
Perhaps not completely working yet. 

test code:
```
    try:
        with open('testfile-deleteme','wb') as f:
            f.buffered.write(b'0')
     except Exception as e:
            print(e)
```
produces error:
`'_io.BufferedRandom' object has no attribute 'buffered'`

cause: opening with mode 'w' produces TextIO (from typing.py:
```
class TextIO(IO[str]):
    """Typed version of the return of open() in text mode."""

    __slots__ = ()

    @abstractproperty
    def buffer(self) -> BinaryIO:
        pass

```

opening with mode 'wb' produces BinaryIO 
```
class BinaryIO(IO[bytes]):
    """Typed version of the return of open() in binary mode."""

    __slots__ = ()

    @abstractmethod
    def write(self, s: Union[bytes, bytearray]) -> int:
        pass

```

recommend:
Use open(...,'wb') and f.write(chunk) for both Python 2 and 3

**Comment by jeffreydwalter** [comment]
I don't really follow what you're getting at. I updated all of the places that were using 'w' to use 'wb'. (I neglected to update the sample code in the wiki, but will do that now.)

**Comment by jeffreydwalter** [comment]
Nevermind, I see what you're talking about now. Will fix. Thanks!

**Comment by jeffreydwalter** [comment]
Okay, should be fixed now. Thanks again!

**Comment by jimletts** [comment]
updated test case for clarity to future readers. Sorry for confusion Jeff

**Comment by jeffreydwalter** [comment]
No problem. Thank you for your input!
