### ISSUE TITLE
Trying to use Arm/Disarm but script just stop

### ISSUE THREAD

**Issue by johan-dahlgren** [jeffreydwalter/arlo#35]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
2.7.13

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'openhab', '4.9.59-v7+', '#1047 SMP Sun Oct 29 12:19:23 GMT 2017', 'armv7l', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
certifi==2017.11.5
chardet==3.0.4
cryptography==1.7.1
dnspython==1.15.0
enum34==1.1.6
idna==2.6
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
monotonic==1.4
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pyxdg==0.25
requests==2.18.4
RPi.GPIO==0.6.3
SecretStorage==2.3.1
six==1.10.0
sseclient==0.0.18
urllib3==1.22

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Basestation VMB3010r2
3 Cameras H7

### What did you do?
Disarm and/or Arm basestation

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
`
#!/usr/bin/env python
from Arlo import Arlo

USERNAME = 'xxx'
PASSWORD = 'xxx'

try:

	arlo = Arlo(USERNAME, PASSWORD)
	basestations = arlo.GetDevices('basestation')

	# Disarm Arlo.
	arlo.Disarm(basestations[0])
	arlo.Logout()
	
except Exception as e:
    print(e)

`

### What did you expect to see?
That the script completes. Now it just stop.
Sometimes it works though, but with no changes from me.

### What did you see instead?
Nothing, the script just stop

### Does this issue reproduce with the latest release?
Yes

**Comment by rittet** [comment]
Use arlo.notify instead. Look up the definition for arm and disarm and change to return the notify-def. 

That worked for my Arlo Q.

**Comment by johan-dahlgren** [comment]
That seems to work fine! Thank You!

**Comment by jeffreydwalter** [comment]
@Ritte88, @johan-dahlgren while changing the library to use Notify() instead of NotifyAndGetResponse() will allow you to set the mode, you will be breaking other methods in the library and not getting any of the responses you get back from Arlo's streaming API.

Please try with my latest commit (from 1/2/2018). There was a race condition happening due to some refactoring that I did a couple weeks ago.

**Comment by johan-dahlgren** [comment]
Just want to confirm that it is working with the latest commit!
Thanks!
