### ISSUE TITLE
Adjust camera brightness

### ISSUE THREAD

**Issue by petewills** [jeffreydwalter/arlo#37]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
xnu-3789.72.11~1/RELEASE_X86_64', machine='x86_64', processor='i386'

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Pro 

### What did you do?
The package is great - no problems whatsoever on my mac.

I would like to adjust the camera brightness for recordings - make the brightness higher at night. On the app, you select 'Live' and it shows a toolbar below the video screen that has a brightness adjuster. I do not see how to do this in the library. 

Is this possible?

**Comment by jeffreydwalter** [comment]
It is possible. I added a method for you to do so, named AdjustBrightness() here: https://github.com/jeffreydwalter/arlo/commit/df42bb4f55e2952c75dbe785ac5f65347965d167

An example of using it would be something like:
```
try:
    arlo = Arlo(USERNAME, PASSWORD)
    print('Logged In')
    
    basestation = arlo.GetDevices('basestation')[0]
    print('got basestations')
    print(basestation)

    camera = arlo.GetDevices('camera')[0]
    print('got cameras')
    print(camera)

    print("Adjusting Brightness")
    # Turn brightness all the way down (2 is all the way up)
    print(arlo.AdjustBrightness(basestation, camera, -2))
    print("Brightness Adjusted")
except Exception as e:
    print(e)
```
