### ISSUE TITLE
Database is currently down

### ISSUE THREAD

**Issue by rakeshdas1** [jeffreydwalter/arlo#4]
I wrote a script very similar to the one that was given in the README file to download the videos from the Arlo dashboard, but I am getting an error that says that the database is currently down. 

```
('GetRecordings failed', {u'data': {u'message': u'We are sorry, the database service is currently down. Please try again.', u'reason': u'DynamoDB Servi
ce Unreachable', u'error': u'2603'}, u'success': False})
```
Has anyone else faced this issue?

**Comment by jeffreydwalter** [comment]
I @rakeshdas1, I have never encountered that error. Can you paste your script (or a gist) so I can take a look at it?

**Comment by rakeshdas1** [comment]
@jeffreydwalter Sure, [here](https://gist.github.com/rakeshdas1/68db665c61e8c3b21d31d9b5ab0497e0) it is!

**Comment by jeffreydwalter** [comment]
I left a comment in your gist. Basically, your date format is wrong in your strftime() calls. 

It's should be ```"%Y%m%d"```, not ```"%m%d%Y"```.

**Comment by rakeshdas1** [comment]
Ah, thanks!
