### ISSUE TITLE
Download Recording from multiple Cameras

### ISSUE THREAD

**Issue by JackVVo** [jeffreydwalter/arlo#40]
Hi, I follow the downloading sample and I was able to get only one camera recording download for the day... I have currently setup 2 camera, how can I download both devices video?

**Comment by jeffreydwalter** [comment]
Did you ever get your code working?

**Comment by JackVVo** [comment]
No... I try to do everything... get devices and use device to get download.. Maybe I do something wrong.. may you help?

**Comment by JackVVo** [comment]
I will also definitely buy you a beer for helping me out! sober up :-)

**Comment by jeffreydwalter** [comment]
So, @JackVVo I'm happy to help you, but you completely ignored the issue template. I am going to close this issue. Please read https://github.com/jeffreydwalter/arlo/wiki/Issue-Guidelines-and-Policies and open a new issue following the guidelines.

Thanks.
