### ISSUE TITLE
SubscribeToMotion events stops working when Presence Server is unreachable

### ISSUE THREAD

**Issue by chiradeep** [jeffreydwalter/arlo#46]
Please answer these questions before submitting your issue. Thanks!

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.0.2
asn1crypto==0.24.0
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
cryptography==2.1.4
enum34==1.1.6
idna==2.6
ipaddress==1.0.19
mcpi==0.1.1
mippy==0.1
monotonic==1.4
numpy==1.6.2
pexpect==4.2.1
picamera==1.10
pifacecommon==4.1.2
pifacedigitalio==3.0.4
playsound==1.2.2
ptyprocess==0.5.1
pycparser==2.18
pygobject==3.8.2
pyOpenSSL==17.5.0
pyserial==2.5
PySocks==1.6.8
requests==2.18.4
RPi.GPIO==0.6.2
six==1.11.0
sseclient==0.0.18
urllib3==1.22

### What did you do?
Used examples/arlo-motiondetect.py to subscribe to motion detection. It worked for about 24 hours.

### What did you expect to see?
Works forever

### What did you see instead?
Exception in a ping thread, but the program continued to run (did not reach my exception handler). No motion detection events were received after that event.
Exception:
xception in thread PingThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 259, in Ping
    self.Notify(basestation, {"action":"set","resource":"subscriptions/"+self.user_id+"_web","publishResponse":False,"properties":{"devices":[basestation_id]}})
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 340, in Notify
    self.request.post('https://arlo.netgear.com/hmsweb/users/devices/notify/'+body['to'], body, headers={"xcloudId":basestation.get('xCloudId')})
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 133, in post
    return self._request(url, 'POST', params, headers)
  File "/usr/local/lib/python2.7/dist-packages/Arlo.py", line 124, in _request
    raise Exception('Request ({0} {1}) failed'.format(method, url), body)
Exception: ('Request (POST https://arlo.netgear.com/hmsweb/users/devices/notify/XXXXXXXXX) failed', {u'data': {u'message': u'We are sorry, the messaging service is currently down.  Please try again February 16, 2018, 02:13 PM UTC.', u'reason': u'Presence Server Unreachable', u'error': u'2601'}, u'success': False})

### Does this issue reproduce with the latest release?
tried with 1.0

**Comment by jeffreydwalter** [comment]
Thanks for the report. I need to make a release which has a fix for that, which is already in master. I'll try to get that it today.

**Comment by jeffreydwalter** [comment]
@chiradeep I just uploaded 1.0.3 to pypi, please upgrade the arlo package by running this command: `pip install arlo --upgrade`.

Thanks!
