### ISSUE TITLE
No connection adapters were found for rtsps

### ISSUE THREAD

**Issue by jayspang** [jeffreydwalter/arlo#47]
### What version of Python are you using (`python -V`)?
Python 2.7.12 (also tried 3.6.4) Ubuntu (also tried Win10)

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'hostname', '4.10.0-38-generic', '#42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017', 'x86_64', 'x86_64')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
adium-theme-ubuntu==0.3.4
arlo==1.0.3
awscli==1.11.115
botocore==1.5.78
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.7
docutils==0.13.1
futures==3.1.1
idna==2.6
jmespath==0.9.3
monotonic==1.4
pyasn1==0.2.3
pygobject==3.20.0
PySocks==1.6.8
python-dateutil==2.6.0
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.10
six==1.11.0
sseclient==0.0.18
unity-lens-photos==1.0
urllib3==1.22

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo (not pro)

### What did you do?
When trying to download a snapshot, I get the error `No connection adapters were found for 'rtsps://vzwow384-z2-prod.vz.netgear.com:443/vzmodulelive/<url_redacted>'
`. I was able to repro this on a Windows 10 box (both in Bash and Cmd, python 2.7 and python 3.4) as well as a straight-up Ubuntu box. 

I wondered if there was a dependency I'm missing, but I googled the error and couldn't find much useful information. I didn't see anything relating to this in the repo's Wiki.

Here is the code. Note that if I remove the DownloadSnapshot() call, everything works fine.
``` python
from Arlo import Arlo

USERNAME = 'arlo_user@mail.com'
PASSWORD = 'supersecret'

try:
    arlo = Arlo(USERNAME, PASSWORD)
    cameras = arlo.GetDevices('camera')
    snapshot_url = arlo.TakeSnapshot(cameras[0])
    arlo.DownloadSnapshot(snapshot_url, "snapshot.jpg")
except Exception as e:
    print(e)
```

**Comment by jeffreydwalter** [comment]
@jayspang that method isn't really well named. The url that's being returned is not the url for the snapshot, but the url for the video stream for the camera you passed to it.

In order to call the api TakeSnapshot() uses under the covers you have start the camera video feed. This function mimics what happens when you start recording video in the UI and then click the camera icon to take a snapshot. So, really... It's more like "TriggerStreamSnapshot()". :)

If you just want to take a snapshot, you should use TriggerFullFrameSnapshot(), which doesn't require the camera video feed to be active.

Try this:
```
from Arlo import Arlo

USERNAME = 'arlo_user@mail.com'
PASSWORD = 'supersecret'

try:
    arlo = Arlo(USERNAME, PASSWORD)
    camera = arlo.GetDevices('camera')[0]
    basestation = arlo.GetDevices('basestation')[0]
    url = arlo.TriggerFullFrameSnapshot(basestation, camera)
    arlo.DownloadSnapshot(url, 'snapshot.jpg')
except Exception as e:
    print(e)
```

I went ahead and renamed that function and added some comments to the function header to make it clear that you should only call TakeStreamSnapshot() if you're already streaming video.

**Comment by jayspang** [comment]
@jeffreydwalter thanks for the prompt response! I appreciate the help trying to get up and running with this. :)

When I run `TakeSnapshot()`, a new snapshot appears in the "Library" section of Arlo's web interface, so it appeared that function was working correctly. However, your explanation certainly covers why `DownloadSnapshot()` was not. Might I recommend updating the example docs? (specifically [here ](https://github.com/jeffreydwalter/arlo/blob/master/examples/arlo-snapshot.py#L26) and [here](https://github.com/jeffreydwalter/arlo/wiki/Record-Video-and-Taking-Snapshots))

Do you happen to know how to update the "Thumbnail" that appears on the Arlo page/app when viewing all of your cameras? I had hoped that `TakeSnapshot()` would cause this thumbnail to update, so I could write a script to update them every _n_ minutes. However, it doesn't seem to do the trick! 

Failing that I'll probably have to publish my own website (maybe in AWS) with the snapshots of each cam so I can check on things with a quick glance.

**Comment by jeffreydwalter** [comment]
No problem. I updated the sample code to reflect the changes I made. Thanks for pointing out my omission.

That thumbnail is actually just the full-framed image, resized using css. If you inspect the img element you will see that it's coming from this url:
```
<img camera-thumbnail="" style="z-index: 1;" src="https://arlolastimage-z2.s3.amazonaws.com/a1289c23_7476_4b79_ab4f_XXXXXXXXXXXX/XXX-XXXXXXXXXX/XXXXXXXXXXX/lastImage.jpg?AWSAccessKeyId=XXXXXXXXXXXXXXXX&Expires=1519166628&Signature=XXXXXXXXXXXXXXXXXXX">
```

I honestly don't know how to force an update of that image. I assume that it happens whenever your camera detects motion. You should make your code pull from the lastimage.jpg url (you can get it from a call to `GetDevices("camera")[0].get('presignedLastImageUrl')`
If the camera actually detected motion that url should reflect that fact.

**Comment by jayspang** [comment]
@jeffreydwalter I'm sorry if this is not the correct place to keep asking you questions, but I'm not sure if this is related to your solution or not.

I changed the script to the code you mentioned above and it works... sometimes. Sometimes it works, and sometimes it hangs on this line indefinitely (at least, I get bored and CTRL+C the program after 10 minutes or so).

`url = arlo.TriggerFullFrameSnapshot(basestation, camera)`

Is there any added logging I can inspect to see where this is getting hung up? Is this something you've experienced before?

**Comment by jeffreydwalter** [comment]
@jayspang no worries, you're in the right spot.

Do you have time to join a Slack screenshare with audio? :) I'm happy to debug it on your box since you're able to reproduce the issue.

**Comment by jayspang** [comment]
@jeffreydwalter I'm afraid I'll have to schedule it. Is tomorrow evening good? (I'm thinking around 7-8pm PST)

**Comment by jeffreydwalter** [comment]
@jayspang I can't tomorrow, how about Thursday? I'm in CST.

**Comment by jayspang** [comment]
That works. I'll add something to my calendar. Thursday at 7pm (PST)?

**Comment by jayspang** [comment]
@jeffreydwalter to get the ball rolling on the troubleshooting, the code gets stuck in [this](https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L425-L427) `if` statement. I added `print event` to L418 and I'm watching the "subscriptions" events roll through indefinitely.

**Comment by jeffreydwalter** [comment]
@jayspang Thursday at 7pm works fine with me. Here's an invite link to my Slack channel https://join.slack.com/t/arlo-dev/shared_invite/enQtMzE4MDkxMjMyMzg3LTM3MzZmYTU1ZmQ5MzExNTExMDA1YjZmMWJmZDFmYWQxYWM4MzU4YjJlZjE4NTY0Y2Q3NDM0Nzg3MzA1OGM4MGE

**Comment by jayspang** [comment]
Hey @jeffreydwalter perhaps we should cancel out meeting.

I still hit the bug sporadically, but I'm not confident I can reproduce it during our call. I set my script to run every 5 minutes via a cron job, and it works more often than not. It will work for hours on end, and then random stop working for 30 minutes (once during the day and once at night).

I'd be happy to share my script with you (as well as the logging I have for successful and failing runs). Let me know if you're interested!

**Comment by jeffreydwalter** [comment]
Hey @jayspang, If you want to join the slack channel and paste your code there, feel free (or you can paste it here if you don't care about sharing it with the world). :) I'll run it and see if I can reproduce it. I'm sure there's a race condition there. The code really needs a good refactoring; I wrote a lot of it before I really understood how the API was really using the eventstream.
