### ISSUE TITLE
Misspelling in Arlo.py line 814

### ISSUE THREAD

**Issue by manluk** [jeffreydwalter/arlo#49]
The current version of Arlo.py has a misspelling in line 814 (baststation instead of basestation):

`stream_url = self.StartStream(baststation, camera)`

**Comment by jeffreydwalter** [comment]
Thanks for catching that! I really need to get some unit tests one of these days...

**Comment by jeffreydwalter** [comment]
Package with bug fix has been posted to pypi.

**Comment by manluk** [comment]
Thanks for fixing the bug. Your component is a really great to integrate Arlo into my house automation.

I found another problem within the method HandleEvents: sometimes I get an empty event, e.g. if I arm or disarm the basestation. In this case the event.get('resource', '') in line 425 fails because event is None and event_stream_stop_event.is_set() is true (see line 419). For this case I changed the code from line 425 like this (added line "if event != None"):

```
                if event != None:
                    if event.get('resource', '').startswith('subscriptions'):
                        self.event_streams[basestation_id].queue.put(event)
                        time.sleep(0.05)
                    else:
                        response = callback(self, event)
                        # NOTE: Not ideal, but this allows you to look for a specific event and break if you want to return it.
                        if response is not None:
                            return response

```

Could you please handle this case in your code too?

**Comment by jeffreydwalter** [comment]
@manluk GREAT catch! Thank you! I pushed a fix for that and pushed a new release to pypi.
