### ISSUE TITLE
SSL error 400 Client Error

### ISSUE THREAD

**Issue by jbedgood** [jeffreydwalter/arlo#50]
Please answer these questions before submitting your issue. Thanks!

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)? arlo==1.0.8
beautifulsoup4==4.5.3
chardet==2.3.0
chrome-gnome-shell==0.0.0
cryptography==1.7.1
DateTime==4.2
enum34==1.1.6
html5lib==0.999999999
idna==2.2
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
lxml==3.7.1
monotonic==1.4
numpy==1.12.1
pyarlo==0.1.2
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pyOpenSSL==16.2.0
PySocks==1.6.8
pytz==2018.3
pyxdg==0.25
requests==2.12.4
scour==0.32
SecretStorage==2.3.1
six==1.10.0
sseclient==0.0.19
sseclient-py==1.7
urllib3==1.19.1
webencodings==0.5
zope.interface==4.4.3

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Base station: VMB3010r2
Cameras: Arlo hardware version: H7

### What did you do? used the download/delete videos script get error
400 Client Error: Bad Request for url: https://arlo.netgear.com/hmsweb/users/library/recycle

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
I used the following in a python script:
```
from Arlo import Arlo

from datetime import timedelta, date
import datetime
import sys

USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:
	# Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
	# Subsequent successful calls to login will update the oAuth token.
	arlo = Arlo(USERNAME, PASSWORD)
	# At this point you're logged into Arlo.

	today = (date.today()-timedelta(days=0)).strftime("%Y%m%d")
	seven_days_ago = (date.today()-timedelta(days=7)).strftime("%Y%m%d")

	# Get all of the recordings for a date range.
	library = arlo.GetLibrary(seven_days_ago, today)

	# Iterate through the recordings in the library.
	for recording in library:

		videofilename = datetime.datetime.fromtimestamp(int(recording['name'])//1000).strftime('%Y-%m-%d %H-%M-%S') + ' ' + recording['uniqueId'] + '.mp4'
		##
		# The videos produced by Arlo are pretty small, even in their longest, best quality settings,
		# but you should probably prefer the chunked stream (see below). 
		###    
		#    # Download the whole video into memory as a single chunk.
		#    video = arlo.GetRecording(recording['presignedContentUrl'])
		#	 with open('videos/'+videofilename, 'wb') as f:
		#        f.write(stream)
		#        f.close()
		# Or:
		#
		# Get video as a chunked stream; this function returns a generator.
		stream = arlo.StreamRecording(recording['presignedContentUrl'])
		with open('videos/'+videofilename, 'wb') as f:
			for chunk in stream:
				f.write(chunk)
			f.close()

		print('Downloaded video '+videofilename+' from '+recording['createdDate']+'.')

	# Delete all of the videos you just downloaded from the Arlo library.
	# Notice that you can pass the "library" object we got back from the GetLibrary() call.
	result = arlo.BatchDeleteRecordings(library)

	# If we made it here without an exception, then the videos were successfully deleted.
	print('Batch deletion of videos completed successfully.')

except Exception as e:
    print(e)
```
### What did you see instead? error
400 Client Error: Bad Request for url: https://arlo.netgear.com/hmsweb/users/library/recycle

### Does this issue reproduce with the latest release?
I've only used the latest version

**Comment by jeffreydwalter** [comment]
@jbedgood thanks for reporting this. The problem is that your call to GetLibrary() isn't returning any data, presumably because you don't have any recordings.

I will update the BatchDeleteRecordings() and DeleteRecording() methods to just do a no-op if you pass an empty array to them.

**Comment by jeffreydwalter** [comment]
Should work better now. Thanks!

**Comment by jbedgood** [comment]
How do I get that change now?

**Comment by jeffreydwalter** [comment]
sudo pip install arlo --upgrade
