### ISSUE TITLE
Install issues on Synology Diskstation 214play

### ISSUE THREAD

**Issue by edraven** [jeffreydwalter/arlo#51]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.12

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'DrishStation', '3.2.40', '#15254 SMP PREEMPT Fri Jan 26 06:38:43 CST 2018', 'i686', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.0.9
certifi==2018.1.18
chardet==3.0.4
idna==2.6
monotonic==1.4
nose==1.3.7
PySocks==1.6.8
requests==2.18.4
rt==1.0.10
six==1.11.0
sseclient==0.0.19
urllib3==1.22

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Original Arlo

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
python arlo-download.py 
Traceback (most recent call last):
  File "arlo-download.py", line 1, in <module>
    from Arlo import Arlo
  File "/usr/lib/python2.7/site-packages/Arlo.py", line 24, in <module>
    import monotonic
  File "/usr/lib/python2.7/site-packages/monotonic.py", line 169, in <module>
    raise RuntimeError('no suitable implementation for this system: ' + repr(e))
RuntimeError: no suitable implementation for this system: RuntimeError('can not find library rt',)

### What did you expect to see?
rt is installed, so wasn't expecting it to say it's missing

**Comment by jeffreydwalter** [comment]
So this is an issue with monotonic, sorta... See https://github.com/atdt/monotonic/issues/23

**Comment by jeffreydwalter** [comment]
Did that help you? You basically need to update your PATH variable on your NAS to include one or more of those binaries monotonic is looking for.

**Comment by jeffreydwalter** [comment]
@edraven did you figure this out? If not, I'm happy to help. If so, please let me know so I can resolve this issue.

**Comment by jeffreydwalter** [comment]
Closed due to inactivity.
