### ISSUE TITLE
No longer able to view live stream

### ISSUE THREAD

**Issue by Bradley225** [jeffreydwalter/arlo#53]
Hi, I am using python 2.7 on OSX and was able to view live stream via ffplay up until recently using the following code and running it in terminal or Home assistant, not sure when it stopped working as only purchased new batteries yesterday!

I get the following error in terminal when trying to call this function. I have also tried subscribing to basestation as per examples but it worked for me without before it stopped working so pasting the code without subscribe.

 'EventStream' object has no attribute 'event_stream_thread'

Any help greatly appreciated.

    arlo = Arlo(USERNAME, PASSWORD)
    cameras = arlo.GetDevices('camera')
    basestations = arlo.GetDevices('basestation')
    url = arlo.StartStream(cameras[0])
    
    p = Popen(['ffplay', '-i', url,  '-format', 'h264', '-x', '360', '-y', '210', '-noborder'])
    return True;

**Comment by jeffreydwalter** [comment]
Hey Brad, can you please fill out the issue template? It's there for a reason.

**Comment by jeffreydwalter** [comment]
https://github.com/jeffreydwalter/arlo/wiki/Issue-Guidelines-and-Policies
