### ISSUE TITLE
Live Streaming no longer working for me

### ISSUE THREAD

**Issue by Bradley225** [jeffreydwalter/arlo#54]
Python 2.7.10

('Darwin', Brads-MacBook-Pro.local', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64', 'x86_64', 'i386')

altgraph==0.10.2
arlo==1.0.9
asn1crypto==0.24.0
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
cryptography==2.1.4
enum34==1.1.6
idna==2.6
ipaddress==1.0.19
libpurecoollink==0.4.2
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
monotonic==1.4
ndg-httpsclient==0.4.3
netifaces==0.10.6
numpy==1.8.0rc1
paho-mqtt==1.3.0
py2app==0.7.3
pyarlo==0.1.2
pyasn1==0.4.2
pycparser==2.18
pycryptodome==3.4.6
pyharmony==1.0.18
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==17.5.0
pyparsing==2.0.1
PySocks==1.6.8
python-dateutil==1.5
pytz==2013.7
requests==2.18.4
scipy==0.13.0b1
six==1.11.0
sleekxmpp==1.3.3
sseclient==0.0.18
sseclient-py==1.7
urllib3==1.22
xattr==0.6.4
zope.interface==4.1.1

Arlo original (not pro) cameras and basestation

After getting live streaming working using this arlo library and ffplay using terminal a few months ago it has now stopped working so after going back to calling the python script and testing in Terminal on OSX I get the following errors when calling arlo.StartStream(cameras[2]) - TypeError: StartStream() takes exactly 3 arguments (2 given) - so after looking at the src code of arlo.py I initalize basestations this time and change to arlo.StartStream(basestations[0], cameras[2]) but this time I get error 'EventStream' object has no attribute 'event_stream_thread' for line 85 of arlo.py when calling StartStream. note: I am testing camera 2 because cam 0 and 1 are not currently in use. I can't seem to get past StartStream anymore.

def test_method():
    arlo = Arlo(USERNAME, PASSWORD)
    cameras = arlo.GetDevices('camera')
    basestations = arlo.GetDevices('basestation')
    url = arlo.StartStream(basestations[0], cameras[2])
    self.p = Popen(['ffplay', '-i', url,  '-format', 'h264', '-x', '360', '-y', '210', '-noborder'])

I hoped to see live streaming of my Arlo Camera in a ffplay window.

Errors are seen instead in the terminal window described above.

I have installed the latest version by calling pip install arlo

Any help appreciated.

Further trace output is below in case it helps..

  File "./hello_world.py", line 17, in test_method
    url = arlo.StartStream(basestations[0], cameras[2])
  File "/Library/Python/2.7/site-packages/Arlo.py", line 765, in StartStream
    return self.TriggerAndHandleEvent(basestation, trigger, callback)
  File "/Library/Python/2.7/site-packages/Arlo.py", line 445, in TriggerAndHandleEvent
    self.Subscribe(basestation)
  File "/Library/Python/2.7/site-packages/Arlo.py", line 299, in Subscribe
    self.event_streams[basestation_id].Start()
  File "/Library/Python/2.7/site-packages/Arlo.py", line 85, in Start
    self.event_stream_thread.start()

**Comment by jeffreydwalter** [comment]
Thanks for refiling the issue! I'm out and about today, but will look into this tonight.

**Comment by Bradley225** [comment]
Thank you.

**Comment by jeffreydwalter** [comment]
I'm not able to reproduce your issue. It seems like you're probably getting an exception in this code: https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L50-L55
Please remove lines 50, 54, and 55 and try your code again. Also, are you sure the camera you're referencing is on and enabled?

**Comment by Bradley225** [comment]
Thanks, unfortunately that didn't fix it.

I have tried removing lines 50, 54 & 55 as you suggested and also made sure I was using the file you linked to.

The trace I get is

  File "/Library/Python/2.7/site-packages/Arlo.py", line 764, in StartStream
    return self.TriggerAndHandleEvent(basestation, trigger, callback)
  File "/Library/Python/2.7/site-packages/Arlo.py", line 444, in TriggerAndHandleEvent
    self.Subscribe(basestation)
  File "/Library/Python/2.7/site-packages/Arlo.py", line 297, in Subscribe
    self.event_streams[basestation_id] = EventStream(QueueEvents, Heartbeat, args=(self, ))
  File "/Library/Python/2.7/site-packages/Arlo.py", line 51, in __init__
    event_stream = sseclient.SSEClient('https://arlo.netgear.com/hmsweb/client/subscribe?token='+self.arlo.request.session.headers.get('Authorization'), session=self.arlo.request.session)
TypeError: __init__() got an unexpected keyword argument 'session'
Exception AttributeError: "'EventStream' object has no attribute 'event_stream_thread'" in <bound method EventStream.__del__ of <Arlo.EventStream object at 0x10853add0>> ignored

What confuses me also which might be related is that all the examples seem to show that only 1 argument is required for StartStream but I get an error that only 2 arguments have been passed and 3 are required if I only pass cameras[2] to StartStream so I am passing basestations[0] as the first argument also as mentioned in my previous post to get rid of that error.

**Comment by jeffreydwalter** [comment]
Thanks for that. The purpose of removing those lines was just to see what exception was begin caught and not reported. So, after seeing that and looking at what packages you have installed, I believe your issue is related to the fact that you have both of these packages installed:
```
sseclient==0.0.18
sseclient-py==1.7
```
Please remove `sseclient-py` and try again.

**Comment by jeffreydwalter** [comment]
Also, the issue with the number of arguments is my bad. I made some changes to the API and obviously missed some of the example code. I will update that to reflect the current state of the API.

Thanks!

**Comment by Bradley225** [comment]
You are a life saver, thank you so much remove sseclient-py has fixed the problem as you said. Great spot :)

**Comment by jeffreydwalter** [comment]
Awesome! I'm glad to hear that fixed it. I REALLY need to document that somewhere, as you are not the first person to get bitten by that... :)

Thanks again for bringing the out of date docs and example code to my attention. That should all be better now too.
