### ISSUE TITLE
Question on setting custom mode

### ISSUE THREAD

**Issue by cbsweig** [jeffreydwalter/arlo#55]
Great work. I see in the examples you can arm and disarm. Have you found a way to set a custom mode? 

Thanks

Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

**Comment by jeffreydwalter** [comment]
Hi @cbsweig, this library has a function for setting custom modes, called:
```
arlo.CustomMode(basestation, mode)
```
You can get the modes by calling:
```
arlo.GetModes(basestation)
```

**Comment by cbsweig** [comment]
Excellent news.  I'm traveling this week and will try when I get back home.  There is a thread (https://community.netgear.com/t5/Arlo-Idea-Exchange/Enable-Custom-Modes-from-IFTTT/idi-p/1260020) where this has been in issue to automate from IFTTT... with your library and this function I see a great solution. 

Again - thanks for the excellent work.

**Comment by jeffreydwalter** [comment]
@cbsweig I'm closing this, as I assume you got what you needed. If not, please leave a comment here and I'll reopen the issue. Thanks!
