### ISSUE TITLE
Did Arlo change something?

### ISSUE THREAD

**Issue by LenShustek** [jeffreydwalter/arlo#56]
Did Arlo change something about their protocol in the last few weeks?

My RaspberryPI-based gadgets that arm and disarm my cameras have been working fine for two years with the September 2016 version of this library, but they have suddenly started getting authorization errors. I haven't changed anything, not even my login info.

I can start the process of upgrading to the latest code, but that will no doubt precipitate a cascade of changes.

**Comment by jeffreydwalter** [comment]
Hi Len,

I'm not aware of any changes. I'll do a little testing later today.

**Comment by jeffreydwalter** [comment]
Hey Len, as far as I can tell, nothing has changed. I logged into their UI and watched the requests. Can you check the system time on your pi?

**Comment by LenShustek** [comment]
The system time is correct, and I've rebooted several times.
It looks like the login succeeds, and then it returns a "401 Client Error: Unauthorized" error while trying "basestations = arlo.GetDevices('basestation')"

**Comment by jeffreydwalter** [comment]
Odd. It works fine for me. I just tested. Stupid question here, but did you happen to change your password or anything like that? 

Edit: Nevermind, I see you said you didn't change your login info.

**Comment by jeffreydwalter** [comment]
Or update any python packages?

**Comment by jeffreydwalter** [comment]
Can you add some debugging to Arlo.py for me? Maybe dump the r in the line that does the http request.
```
r = requests.get(url, headers=headers, cookies=cookies, stream=stream)
```

**Comment by LenShustek** [comment]
Well (blush) I did try updating stuff when it starting failing, so I don't want you to spend a lot of time on this. I might have my PI in an inconsistent state. But it started failing (on both my systems, which use different logins) before I changed anything; I've never changed the userids or passwords.

Using  the original 2-year-old code, logging in appears to succeed.
Before the line "r = requests.get(url, headers=headers)"  in the get function,
the url is 'https://arlo.netgear.com/hmsweb/users/devices'
and headers is {   'Authorization': '2_5ZUbjyTDdO-odN1dYkQIsPeMbWOcrRtLNin0STbxS_ZmIibW32sprYHvcoVToh_HmCLtFY2NhIju7WRdZyPEbjlpeQ2ffllftvJ3b46j8LaTY9weHJ6PBsTfk2U0JyEzGy_Xz0l23M_b1jqnBhLNtzTcieuvdIA75Apj75-PsHhH'}

Then after requests.get  the result r is <Response [401]>
and it raises an exception.

**Comment by LenShustek** [comment]
Guess what? Several weeks after it started failing, it suddenly starting working again, without me doing anything! This is for two different Raspberry Pis controlling different cameras with different account logons in different houses in different cities.  (I had updated the Python version on one of them when the problem started, but the other one hasn't been touched in two years.)

I can only surmise that Arlo temporarily broke something in the way they respond to the commands that your two-year-old code issues, but then fixed it. 

Sorry for the false alarm...

**Comment by jeffreydwalter** [comment]
Great news! Thanks for the update. I would highly recommend checking out the latest and greatest code. The API hasn't changed all that much (it has changed) and there have been several bug fixes and new APIs added. That being said, if it ain't broke... :)
