### ISSUE TITLE
Arlo Baby

### ISSUE THREAD

**Issue by jurgenweber** [jeffreydwalter/arlo#60]
I would like to help extend this code so the Arlo Baby works with all of its features, my main goal would be then to upgrade the HASS Arlo integration. https://github.com/home-assistant/home-assistant/issues/13176

The Arlo baby has a few other features, including:
* the ability to talk on your phone and send audio
* it reports on Temperature, humidity and air quality. https://github.com/jeffreydwalter/arlo/pull/62
* It has a night light you can adjust the brightness for and turn on/off. https://github.com/jeffreydwalter/arlo/pull/64
* It has a media player, where you can play lullabies, etc. (https://github.com/jeffreydwalter/arlo/pull/63)
* has the ability to report on video motion, audio noises and even know the difference between a 'noise' and a baby 'crying', [link](https://www.arlo.com/au/products/arlo-baby/Default.aspx) 'Baby crying alert'.

My python skills are not that great but I will start with working out the API calls, etc.

**Comment by jeffreydwalter** [comment]
@jurgenweber that would be great! I have a Slack channel setup, if you'd like to join. I usually hang out there during work hours (CST) and will respond to any messages there when I can. I'd be happy to do some screen sharing and a little pair programming to get these features into the library.

Here's a link to the Slack channel: https://join.slack.com/t/arlo-dev/shared_invite/enQtMzQxMTcyNjYzMDc5LThkY2QwNmYxYTY3ODM3NTlhZjlkYzlhOTc2MzllMDlmMTBjZTNhODQ0NDViZDZhNWY1NWMyODFiNzk4MmE5MTc

**Comment by jurgenweber** [comment]
ok, so the temp/nightlight and media player are done.

It looks like 'getCameraState' method you can get the details on the motion/audio/crying detection I will do a PR to turn them on/off.

Once I do that, maybe we can do a release?

the first one 'talking and sending audio', not sure if I really need that right now.

**Comment by jeffreydwalter** [comment]
Thanks for banging that stuff out!

**Comment by jurgenweber** [comment]
forgot to mention, I ran into this as well; https://github.com/jeffreydwalter/arlo/issues/54

**Comment by jeffreydwalter** [comment]
I'm not really sure what to do about that. It's documented on the README. I suppose I could add a check when you install the Arlo package and bail if you have the bad package.

**Comment by jurgenweber** [comment]
https://github.com/jeffreydwalter/arlo/pull/65

last one... Lets do a release please? :)

**Comment by jeffreydwalter** [comment]
Merged and release arlo-1.1.0 pushed.

**Comment by jeffreydwalter** [comment]
@jurgenweber you done with this issue? How's everything working?

**Comment by jurgenweber** [comment]
Yeah, it is working fine. I just need to find the time to finish the HASS stuff. :)
