### ISSUE TITLE
User Login authentication issue from netgear website

### ISSUE THREAD

**Issue by axwack** [jeffreydwalter/arlo#66]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
3.6

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Mac OSX

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.0.10
certifi==2018.4.16
chardet==3.0.4
Django==2.0.4
django-cors-headers==2.2.0
django-webpack-loader==0.6.0
djangorestframework==3.8.2
idna==2.6
monotonic==1.4
psycopg2-binary==2.7.4
Pygments==2.2.0
PySocks==1.6.8
pytz==2018.4
requests==2.18.4
six==1.11.0
sseclient==0.0.19
urllib3==1.22

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro V2

### What did you do?
I am currently writing a Django Web wrapper to do CCVR. I created a react Login page that authenticates from a React Front end, sends the username/password by JSON and then I use your library to login. I get the following error when I try to do:

a = Arlo (username,password) 

The following error gets marshalled from the arlo.netgear website.

01 Client Error: Unauthorized for url: https://arlo.netgear.com/hmsweb/login/v2

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
I also tried doing this from the command line and still got the same error. 

### What did you expect to see?
I tried to login via the webpage and it works fine. I expected a successful login 

### What did you see instead?
No error

### Does this issue reproduce with the latest release?
1.0.10

**Comment by jeffreydwalter** [comment]
Without seeing your code it's impossible to tell. I know for 100% fact the login works fine. I would suspect it has something to do with the user/pass you're getting from your JSON API. It's probably encoded improperly or something like that.

**Comment by axwack** [comment]
Posting for now. It was the case where I did not have the right password. My mistake.

I did have a question. If you enter the wrong password into netgear the following JSON response gets sent back. Its in the variable called responseData.

The python code does not retrieve the same response. Do you think there is a way to send this back a calling API?


`def userArloBackend(request):

    data = {}
    try:
        if request.method == 'GET':
            pass

        elif request.method == 'POST':
            status = 200
            data = JSONParser().parse(request)
            arloIn = Arlo(data["email"], data["password"])
            pass
            serializer = UserArloBackendSerializer.UserArloBackendSerializer(data=data)

            return JsonResponse(serializer.errors, status=400)

    except Exception as err:
            if err.response.status_code==400:
                responseData = {
                            'data':
                                {
                                   'error': '2103',
                                   'message': 'The username or password is incorrect.',
                                   'reason': 'The username or password is incorrect'
                                },
                                   'success': 'false'
                }
                return JsonResponse({responseData}, status=400, safe=False)
            if error.response.status_code==401:
                return JsonResponse({"Error: ": "401 Error: Unauthorized Access to https://arlo.netgear.com/hmsweb/login/v2}}"},
                                    status=401)
`

**Comment by jeffreydwalter** [comment]
Okay, I changed the exception thrown so it now returns the response object instead of just the body. Does that help?

**Comment by axwack** [comment]
Thanks Jeff. I realized I could have submitted and done myself. Thanks for doing it. I will fix zand 
Commited myself.
