### ISSUE TITLE
Heartbeat interval

### ISSUE THREAD

**Issue by manluk** [jeffreydwalter/arlo#68]
When I call the subscribe method, the heartbeat thread is started. From this time on the heartbeat thread sends a ping to the Arlo service every 2 seconds. I had some problems with this short interval and changed the ping interval to 90 seconds, but I had to change your code for this modification.

There is an easy way to make the interval configurable: I added the heartbeat interval as an optional parameter to the constructor of Arlo. Here are the changes:

Line 153:
`    def __init__(self, username, password, heartbeatInterval=2):`

Line 163 added:
`        self.heartbeatInterval = heartbeatInterval`

Line 294:
`            while not stop_event.wait(self.heartbeatInterval):`

Could you add these changes to the repository? Or is there any reason to have a heartbeat interval of 2 seconds?

**Comment by jeffreydwalter** [comment]
Hey @manluk, I'm not sure why I have the interval set to 2... That may have been an oversight from testing. It should be something closer to 30 seconds; that's what the website does. I'll fix that real quick.

**Comment by jeffreydwalter** [comment]
Okay, fixed. The latest pip package (arlo-1.1.3) has it.
