### ISSUE TITLE
StartStream doesn't work

### ISSUE THREAD

**Issue by cruiser2016** [jeffreydwalter/arlo#70]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.9

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'cloud', '4.9.0-0.bpo.6-amd64', '#1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13)', 'x86_64', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.1.4
certifi==2018.4.16
cffi==1.9.1
chardet==3.0.4
Cheetah==2.4.4
configobj==5.0.6
cryptography==1.7.1
dnspython==1.12.0
enum34==1.0.3
feedparser==5.1.3
idna==2.6
ipaddress==1.0.16
Markdown==2.6.11
monotonic==1.5
ply==3.4
pyasn1==0.1.9
pycparser==2.10
pycrypto==2.6.1
pyOpenSSL==16.0.0
PySocks==1.6.8
requests==2.18.4
six==1.10.0
sseclient==0.0.19
urllib3==1.22
virtualenv==1.11.6
yenc==0.4.0

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro 2 VMC4030
Arlo Base VMB4000r3

### What did you do?
Tried to run sample code arlo-streamvideo.py using my credential but failed with error message:
Request (POST https://arlo.netgear.com/hmsweb/users/devices/startStream) failed

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

I used the sample code arlo-streamvideo.py and replaced the username and password. No other modification to that code.
I also used the sample code in README.md and that worked.

### What did you expect to see?
test.mp4 file that's not empty.

### What did you see instead?
The error message mentioned above and test.mp4 with 0 byte.

### Does this issue reproduce with the latest release?
Yes

**Comment by jeffreydwalter** [comment]
Works fine for me...

```
$ python test.py 
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --disable-jack --enable-gpl --enable-ffplay --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, rtsp, from 'rtsps://vzwow502-z2-prod.vz.netgear.com:443/vzmodulelive/XXXXXXXXXXXXX_1527782977831?egressToken=XXXXXXXX_3fd5_4d3d_957a_4aae725873e7&userAgent=iOS&cameraId=XXXXXXXXXXXXX__1527782977831':
  Metadata:
    title           : XXXXXXXXXXXXX__1527782977831
  Duration: N/A, start: 0.498333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 24 fps, 24.08 tbr, 90k tbn, 48 tbc
Output #0, mp4, to 'test.mp4':
  Metadata:
    title           : 48B45974D8E54_1527782977831
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1280x720, q=2-31, 24 fps, 24.08 tbr, 90k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x7fd934800000] Non-monotonous DTS in output stream 0:0; previous: 0, current: -18660; changing to 1. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd934800000] Non-monotonous DTS in output stream 0:0; previous: 1, current: -14970; changing to 2. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd934800000] Non-monotonous DTS in output stream 0:0; previous: 2, current: -11190; changing to 3. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd934800000] Non-monotonous DTS in output stream 0:0; previous: 3, current: -7410; changing to 4. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd934800000] Non-monotonous DTS in output stream 0:0; previous: 4, current: -3720; changing to 5. This may result in incorrect timestamps in the output file.
frame=  247 fps= 25 q=-1.0 Lsize=     931kB time=00:00:09.98 bitrate= 763.6kbits/s speed=0.999x    
video:927kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.361359%

🍺  [508] jeff_walter@T2000:~/Code/github/arlo
$ ls -al test.mp4 
-rw-r--r--@ 1 jeff_walter  staff  952903 May 31 11:09 test.mp4
```

**Comment by cruiser2016** [comment]
Thank you Jeff for the reply. I even tried on a new install of python on Windows and got the same error. I wonder if this is to do with my Arlo model?

**Comment by jeffreydwalter** [comment]
Can you please paste the output of you running the script, like I did? I’d like to see EXACTLY what you’re seeing.

**Comment by cruiser2016** [comment]
Please see below for the output and the content of the script. I masked out the credential.

root@cloud:~# python arlostream.py
Request (POST https://arlo.netgear.com/hmsweb/users/devices/startStream) failed

root@cloud:~# cat arlostream.py
from Arlo import Arlo

from subprocess import call

USERNAME = 'xxxxxxxx'
PASSWORD = 'xxxxxxxx'

try:

    # Instantiating the Arlo object automatically calls Login(),
    # which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.

    # Get the list of devices and filter on device type to only get the cameras.
    # This will return an array which includes all of the canera's associated metadata.
    cameras = arlo.GetDevices('camera')

    # Get the list of devices and filter on device type to only get the basestation.
    # This will return an array which includes all of the basestation's associated metadata.
    basestations = arlo.GetDevices('basestation')

    # Send the command to start the stream and return the stream url.
    url = arlo.StartStream(basestations[0], cameras[0])

    # Record the stream to a file named 'test.mp4'.
    # **Requires ffmpeg 3.4 or greater.**
    # For this example, I'm going to open ffmpeg.
    # Crucially important is the '-t' flag, which specifies a recording time. (See the ffmpeg documentation.)
    # This is just a crude example, but hopefully it will give you some ideas.
    # You can use any number of libraries to do the actual streaming. OpenCV or VLC are both good choices.
    # NOTE: This will print the output of ffmpeg to STDOUT/STDERR. If you don't want that, you will
    # need to pass additional arguments to handle those streams.

    call(['ffmpeg', '-re', '-i', url, '-t', '10', '-acodec', 'copy', '-vcodec', 'copy', 'test.mp4'])

except Exception as e:
    print(e)

**Comment by axwack** [comment]
did you put your username and password in the script?This works. I’m using it for my UI.


Vincent Lee

**Comment by jeffreydwalter** [comment]
Are your cameras actually on and enabled?

**Comment by cruiser2016** [comment]
No all cameras are online and active on web and app. I modified the code to print the data and the data is available for camera and basestation, but not for url because startstream is failing. My modified code:
try:

    # Instantiating the Arlo object automatically calls Login(),
    # which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.

    # Get the list of devices and filter on device type to only get the cameras.
    # This will return an array which includes all of the canera's associated metadata.
    cameras = arlo.GetDevices('camera')
    print cameras[0]

    # Get the list of devices and filter on device type to only get the basestation.
    # This will return an array which includes all of the basestation's associated metadata.
    basestations = arlo.GetDevices('basestation')
    print basestations[0]

    # Send the command to start the stream and return the stream url.
    url = arlo.StartStream(basestations[0], cameras[0])
    print(url)

    # Record the stream to a file named 'test.mp4'.
    # **Requires ffmpeg 3.4 or greater.**
    # For this example, I'm going to open ffmpeg.
    # Crucially important is the '-t' flag, which specifies a recording time. (See the ffmpeg documentation.)
    # This is just a crude example, but hopefully it will give you some ideas.
    # You can use any number of libraries to do the actual streaming. OpenCV or VLC are both good choices.
    # NOTE: This will print the output of ffmpeg to STDOUT/STDERR. If you don't want that, you will
    # need to pass additional arguments to handle those streams.

    call(['ffmpeg', '-re', '-i', url, '-t', '10', '-acodec', 'copy', '-vcodec', 'copy', 'test.mp4'])

except Exception as e:
    print(e)

Output:

root@cloud:~# python arlostream.py
{u'deviceName': u'Arlo \u8f66\u9053', u'userId': u'DCW6Q-xxx-xxxxxxxx', u'mediaObjectCount': 0, u'owner': {u'lastName': u'xxxx', u'firstName': u'xxxx', u'ownerId': u'DCW6Q-xxx-xxxxxxxx'}, u'presignedLastImageUrl': u'https://arlolastimage-z1.s3.amazonaws.com/43ba523e_d0b1_432a_b877_xxxxxxxx/DCW6Q-xxx-xxxxxxxx/yyyyyyyy/lastImage.jpg?AWSAccessKeyId=zzzzzzzzzzzz&Expires=1527873942&Signature=zzzzzzzzzzzzzzzzzzzzz', u'displayOrder': 0, u'state': u'removed', u'deviceType': u'camera', u'firmwareVersion': u'1.092.0.6_15695', u'uniqueId': u'DCW6Q-xxx-xxxxxxxx_yyyyyyyy', u'parentId': u'aaaaaaaaaa', u'presignedSnapshotUrl': u'https://arlos3-prod-z1.s3.amazonaws.com/43ba523e_d0b1_432a_b877_xxxxxxxx/DCW6Q-xxx-xxxxxxxx/yyyyyyyy/snapshot.jpg?AWSAccessKeyId=zzzzzzzzzzzzz&Expires=1527873942&Signature=zzzzzzzzzzzzzzzzzzzzz', u'modelId': u'VMC4030', u'userRole': u'OWNER', u'interfaceSchemaVer': u'3', u'dateCreated': 1511634147803, u'deviceId': u'yyyyyyyy', u'properties': {u'olsonTimeZone': u'America/New_York', u'hwVersion': u'H8', u'modelId': u'VMC4030'}, u'interfaceVersion': u'i003', u'lastImageUploaded': u'true', u'lastModified': 1527787541998, u'xCloudId': u'xxxxx-xxxx-xxx-xxxxxxxx', u'presignedFullFrameSnapshotUrl': u'https://arlos3-prod-z1.s3.amazonaws.com/43ba523e_d0b1_432a_b877_xxxxxxxx/DCW6Q-xxx-xxxxxxxx/yyyyyyyy/fullFrameSnapshot.jpg?AWSAccessKeyId=zzzzzzzzzzzzz&Expires=1527873942&Signature=zzzzzzzzzzzzzzzzzzzzz'}

{u'deviceName': u'Arlo Base', u'properties': {u'olsonTimeZone': u'America/New_York', u'hwVersion': u'VMB4000r3', u'modelId': u'VMB4000'}, u'mediaObjectCount': 0, u'automationRevision': 536, u'lastModified': 1527787568522, u'userId': u'DCW6Q-xxx-xxxxxxxx', u'displayOrder': 3, u'dateCreated': 1513388901143, u'connectivity': {u'connected': True, u'type': u'ethernet', u'mepStatus': u'unknown'}, u'state': u'provisioned', u'deviceType': u'basestation', u'deviceId': u'yyyyyyyy', u'uniqueId': u'DCW6Q-xxx-xxxxxxxx_yyyyyyyy', u'interfaceVersion': u'i005', u'owner': {u'lastName': u'xxxx', u'firstName': u'xxxx', u'ownerId': u'DCW6Q-xxx-xxxxxxxx'}, u'interfaceSchemaVer': u'7', u'modelId': u'VMB4000', u'xCloudId': u'xxxxxxxx-xxx-xxx-xxxxxxxx', u'firmwareVersion': u'1.10.0.4_20963', u'userRole': u'OWNER'}
Request (POST https://arlo.netgear.com/hmsweb/users/devices/startStream) failed

**Comment by jeffreydwalter** [comment]
Your camera is `state: removed`, it should be `state: provisioned`. That's your problem.

**Comment by jeffreydwalter** [comment]
I'm not 100% sure what "removed" means, I've never had any of my cameras in that state. Are you absolutely sure your camera is connected to your basestation? Can you stream from it via the browser or app?

**Comment by cruiser2016** [comment]
I am able to stream from browser and app. Just tested again and all four cameras I have showed up and streamed live without any problem in browser and app. I tried to print other cameras and they all have the state as removed.

I wonder if this is due to my camera being Pro 2 model?

**Comment by jeffreydwalter** [comment]
Camera model shouldn't matter. Run this script and paste the output here:
```
from Arlo import Arlo

import json
import re

USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

try:
    arlo = Arlo(USERNAME, PASSWORD)
    
    devices = arlo.GetDevices()
    for i, device in enumerate(devices):
        for key in ['deviceId', 'parentId', 'uniqueId', 'userId', 'xCloudId']:
            if key in device:
                device[key] = re.sub(r'[0-9A-Za-z]', r'X', device.get(key))

        for key in ['deviceName', 'presignedFullFrameSnapshotUrl', 'presignedLastImageUrl', 'presignedSnapshotUrl']:
            device[key] = ""

        device['owner']['ownerId'] = re.sub(r'[0-9A-Za-z]', r'X', device['owner']['ownerId'])
        device['owner']['firstName'] = ""
        device['owner']['lastName'] = ""
        
        devices[i] = device

    pp(devices)
except Exception as e:
    print(e)
```

**Comment by cruiser2016** [comment]
Something wrong with my account, that I have 4 cameras but Arlo somehow has 5 under my account. I picked one that has "provisioned" as its state and that worked.

**Comment by jeffreydwalter** [comment]
Yep, figured it was something like that. :)
