### ISSUE TITLE
Using ARLO API with while listening for events

### ISSUE THREAD

**Issue by mattes-bru** [jeffreydwalter/arlo#71]
Hi @jeffreydwalter,

First let me thank you for your project. From what I see, this is the most mature library for the ARLO environment. What I want to do with the ARLO system  (ARLO Baby) is to improve the homekit integration, using my existing homebridge setup. For that I need:
1. listen for alerts 
2. periodically read the sensors data (temp, hum, air quality)
3. enable / disable the camera 

With the examples I can either do listen for alerts or read sensor data / control the cam.

I tried to combine them in 2 ways, but none of both seems to be working:

1. I used threading.Timer to periodically read the sensors but this seems to cause problems in the HandleEvents() method. Is your arlo api capable of been used multithreaded? 
2. I set a low timeout in the HandleEvents method. But this function never returns but rather raises an unspecified exception. I tracked this down to the EventStream class and its Get method ( I am using python 2.7)

To make this a issue or better a feature request: Can you provide some examples or documentation on this usage?

Regards
Matthias

**Comment by jeffreydwalter** [comment]
@mattes-bru you can definitely do what you are describing with this library. If you want to poll for events, take a look at the `SubscribeToMotionEvents()` method. That method is specific to motion events, but you can generalize it to handle any type of event. I don't see why you can't run it in it's own thread. 
To arm/disarm your cameras, you just need to call the `Arm()/Disarm()` methods, there is an example of this in the [Wiki](https://github.com/jeffreydwalter/arlo/wiki/Arming-and-Disarming-Camera).
To read sensor data, there are a bunch of APIs in this library specifically related to the Arlo baby camera. You should be able to call them like you would `Arm()/Disarm()`.

This library should work fine with threads. Can you please elaborate on the issues you're seeing with threads and HandleEvents?

**Comment by mattes-bru** [comment]
@jeffreydwalter your information, that it should work in multithreaded applications helped a lot. I reworked the code until my test script worked (I am not a python expert). Currently I am listening for events using the HandleEvents() method and with another thread I am polling for the sensor data. 

The plan is now, to hook this to an mqtt server, to make the cam accessible from the home bridge environment.

**Comment by jeffreydwalter** [comment]
Thanks for the update and for closing this issue. I'm really glad to hear you got everything working!
