### ISSUE TITLE
Does Arlo.Login not return a JSPON Response on Success?

### ISSUE THREAD

**Issue by axwack** [jeffreydwalter/arlo#72]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)? 
2

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

OSX
### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro 2

Question: Does this not return a success JSON Response?

**Comment by jeffreydwalter** [comment]
The underlying HTTP request does return JSON, but the login method, all methods in my library, consume the `{success:true}` JSON. If success does not equal true, or the request fails the library will raise an HTTPError exception. So there's really no reason for login to return JSON.

**Comment by axwack** [comment]
Is that all that returns? I wanted to pass along to my UI request but manufactured it on my own. The reason I wanted it was because I can’t see a 200 status on the Object so I can’t tell if it’s logged in or not. 
Vincent Lee
axwack@gmail.com
203.273.3860

**Comment by jeffreydwalter** [comment]
If the Login call doesn't throw an exception, you're logged in.

**Comment by jeffreydwalter** [comment]
When you get the HTTPError you will have access to the response object, so you can get all of the metadata for the http response that way, like this: 
```
try:
    arlo = Arlo(USERNAME, PASSWORD)
except HTTPError as e:
    print(e.response.status_code)
    print(e.response.url)
    print(e.response.text)
    print(e.response.reason)
    print(e.response.headers)
```

Which will output this:
```
401
https://arlo.netgear.com/hmsweb/login/v2
{"data":{"error":"2103","message":"The username or password is incorrect.","reason":"The username or password is incorrect"},"success":false}
Unauthorized
{'X-XSS-Protection': '1; mode=block, 1; mode=block', 'X-Content-Type-Options': 'nosniff', 'transfer-encoding': 'chunked', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Server': 'Server', 'Connection': 'keep-alive', 'X-UA-Compatible': 'IE=edge', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Date': 'Tue, 12 Jun 2018 21:42:14 GMT', 'X-Frame-Options': 'SAMEORIGIN, SAMEORIGIN', 'Content-Type': 'application/json;charset=UTF-8'}
```
