### ISSUE TITLE
Empty basestations list

### ISSUE THREAD

**Issue by mathiaskopo** [jeffreydwalter/arlo#75]
Hi, I'm trying to get a snapshot from a Arlo Go device, using the "Record Video and Triggering Snapshots" example.

But when I run `basestations = arlo.GetDevices('basestation')` I only get an empty list. If I run `cameras = arlo.GetDevices('camera')` then it get my camera. So this makes the `arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])` fail because the basestations list is empty.

Is there another way to get a snapshot, or some way I can get the `arlo.GetDevices('basestation')` to work?

**Updated:**
### What version of Python are you using (`python -V`)?
2.7.14

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Windows 10.0.17134, AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel'

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.1.5
certifi==2018.4.16
chardet==3.0.4
idna==2.7
monotonic==1.5
pyarlo==0.2.0
pyodbc==4.0.22
PySocks==1.6.8
requests==2.19.1
six==1.11.0
sseclient==0.0.19
sseclient-py==1.7
urllib3==1.23
win-inet-pton==1.0.1

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Go

### What did you do?
Tried the "Record Video and Triggering Snapshots" example

### What did you expect to see?
An image from the camera

### What did you see instead?
A failure, because of empty basestations list

### Does this issue reproduce with the latest release?
I installed the one from pip, I guess that is the latest?

**Comment by jeffreydwalter** [comment]
@mathiaskopo, Go cameras ARE their own basestation. So just pass the camera object for both the camera and basestation arguments.

`arlo.TriggerFullFrameSnapshot(cameras[0], cameras[0])`

**Comment by mooniper** [comment]
Hi Jeffrey. Thank you for your response. I'm also trying to get this image from an Arlo Go, and after trying your method of using "cameras[0]" to pass it as parameter instead of "basestations[0]", it's still giving me the same error which reads: "'EventStream' object has no attribute 'event stream thread'". I can see that the array cameras[0] is valid and it has the my camera object. I can see all the properties when I do a print(cameras[0]), so I know it's working. However, I have not been able to use many of the functions available because my "basestations[0]" is empty and it fails when I pass it "cameras[0]". Please let us know your thoughts. Thank you!

**Comment by mathiaskopo** [comment]
Just like mooniper, I can't get it to work using `arlo.TriggerFullFrameSnapshot(cameras[0], cameras[0])` either. I tried doing the http calls "manual" as shown on [robertogallea.com](http://www.robertogallea.com/blog/netgear-arlo-api) and was succesful able to recieve a photo that way, but not when using your python module.

**Comment by jeffreydwalter** [comment]
Can you guys please provide a script the reproduces the issue? Also, can you please read this https://github.com/jeffreydwalter/arlo/wiki/Issue-Guidelines-and-Policies. Thanks.

**Comment by mathiaskopo** [comment]
I followed the example at https://github.com/jeffreydwalter/arlo/wiki/Record-Video-and-Triggering-Snapshots. Below I have shown the process entering each line one by one in IDLE. I have also updated my first comment with system/software info.

>>> from Arlo import Arlo
>>> arlo = Arlo(USERNAME, PASSWORD)
>>> basestations = arlo.GetDevices('basestation')
>>> cameras = arlo.GetDevices('camera')
>>> url = arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    url = arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])
IndexError: list index out of range
>>> url = arlo.TriggerFullFrameSnapshot(cameras[0], cameras[0])

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    url = arlo.TriggerFullFrameSnapshot(cameras[0], cameras[0])
  File "C:\Python27\lib\site-packages\Arlo.py", line 978, in TriggerFullFrameSnapshot
    return self.TriggerAndHandleEvent(basestation, trigger, callback)
  File "C:\Python27\lib\site-packages\Arlo.py", line 456, in TriggerAndHandleEvent
    self.Subscribe(basestation)
  File "C:\Python27\lib\site-packages\Arlo.py", line 310, in Subscribe
    self.event_streams[basestation_id].Start()
  File "C:\Python27\lib\site-packages\Arlo.py", line 91, in Start
    self.event_stream_thread.start()
AttributeError: 'EventStream' object has no attribute 'event_stream_thread'
>>>

**Comment by mathiaskopo** [comment]
I tried using calls directly to the various endpoints (python code below), and can succesful get a snapshot that way.

```
import requests, urllib

#Email, password and random string identifying the request
email = "some@email.com"
password = "some password"
transId = "web!3975ac7b.ebb3a8!1504266382584"

#Start session
headers = {'Content-Type': 'application/json;charset=UTF-8',}
data = '{"email":"'+email+'","password":"'+password+'"}'
response = requests.post('https://arlo.netgear.com/hmsweb/login/v2', headers=headers, data=data)
token = response.json()["data"]["token"]

#Get camera info
headers = {'Authorization': token,}
response = requests.get('https://arlo.netgear.com/hmsweb/users/devices', headers=headers)
xCloudId = response.json()["data"][0]["xCloudId"]
userId = response.json()["data"][0]["userId"]
cameraId = response.json()["data"][0]["deviceId"]
olsonTimeZone = response.json()["data"][0]["properties"]["olsonTimeZone"]

#Start stream
headers = {'Content-Type': 'application/json;charset=UTF-8', 'Authorization': token, 'xcloudId': xCloudId,}
data = '{"to": "'+cameraId+'","from": "'+userId+'","resource": "cameras/"'+cameraId+'","action":"set","publishResponse":true,"transId":"'+transId+'","properties":{ "activityState":"startUserStream","cameraId":"'+cameraId+'"}}'
response = requests.post('https://arlo.netgear.com/hmsweb/users/devices/startStream', headers=headers, data=data)

#Take snapshot
headers = {'Content-Type': 'application/json;charset=UTF-8', 'Authorization': token,  'xcloudId': xCloudId,}
data = '{"parentId": "'+cameraId+'","deviceId": "'+cameraId+'","olsonTimeZone": "'+olsonTimeZone+'"}'
response = requests.post('https://arlo.netgear.com/hmsweb/users/devices/takeSnapshot', headers=headers, data=data)

#Library
headers = {'Content-Type': 'application/json;charset=UTF-8','Authorization': token,}
data = '{"dateFrom": "20180722","dateTo": "20180722"}'
response = requests.post('https://arlo.netgear.com/hmsweb/users/library', headers=headers, data=data)
snapshotURL = response.json()["data"][0]["presignedContentUrl"]
jpgfile = urllib.URLopener()
jpgfile.retrieve(snapshotURL, "snapshot.jpg")
```

**Comment by jeffreydwalter** [comment]
@mathiaskopo thank you! Looks like the library might be raising an exception when starting the SSE stream around [line 54-55](https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L53-L58). Can you comment out lines 54, 57, & 58, and try the script again? I suspect you will see the program raise an exception there...

**Comment by jeffreydwalter** [comment]
Actually... Just noticed you have two different sse client libraries, which I believe is your actual issue.
Please remove `sseclient-py` and try your script.

**Comment by mathiaskopo** [comment]
@jeffreydwalter  Removing the `sseclient-py` library made the `arlo.TriggerFullFrameSnapshot(cameras[0], cameras[0])` work. Thanks a lot!

**Comment by mooniper** [comment]
Thank you very much. Removing the sseclient-py also worked for me. It's working great, thank you for all your help!

**Comment by Troyhard** [comment]
Dear all,

I am new to programming and am wondering:
* What is sseclient-py? I have an folder "sseclient-0.0.24-py3.6.egg-info" in my project folder. Are you talking about this folder? It contains only txt-files and a PKG-INFO
    --> If yes, how do I uninstall this folder or is it just deleting?
    --> If no, what is sseclient-py then and how am I supposed to remove it?

I´d appreciate your help. Thanks
Troy

**Comment by jeffreydwalter** [comment]
https://pypi.org/project/sseclient-py/ is the package you installed. 

Uninstall it like this: `pip uninstall sseclient-py`
