### ISSUE TITLE
Arlo GO toggle on and off not working

### ISSUE THREAD

**Issue by leonfoster** [jeffreydwalter/arlo#76]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.14

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

I am using a Windows 10 machine with the python package in visual studio.
I have a x64-based processor i7-2600

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
I don't think I have done this.

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Alro Go
HW Version H6

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

Attempted to run the toggle camera off function for the Arlo go:
Running this line:

     print(arlo.ToggleCamera(cameras[1], cameras[1], False))

I have had to put the basestation as cameras[1] as the arlo go does not have a basestation. This works for requesting to start and stop recordings. 

### What did you expect to see?
The Alro Go camera to switch off in the netgear controller website, however the camera stays on.

### What did you see instead?

The Arlo go Camera does not switch off.

This gets printed on the console, it appears that it is working.

{'resource': 'cameras/51D1777JA0196', 'action': 'is', 'properties': {'privacyActive': False}, 'transId': 'web!4e71e501.a61dc!1533028525316', 'to': 'KD4HNTP-300-13403994_web', 'from': '51D1777JA0196'}

### Does this issue reproduce with the latest release?
Yes, I have the latest release.

**Comment by jeffreydwalter** [comment]
You're flag is backwards... See https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L658-L659

**Comment by leonfoster** [comment]
Many thanks, I think the comments in the example were misleading so I thought it wasn't working!
