### ISSUE TITLE
StartStream(...) only works if you have a basestation but you don't need a basestation with "arlo baby"

### ISSUE THREAD

**Issue by Haskar** [jeffreydwalter/arlo#77]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.13

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'openHABianPi', '4.14.52-v7+', '#1123 SMP Wed Jun 27 17:35:49 BST 2018', 'armv7l', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.1.6
certifi==2018.4.16
chardet==3.0.4
cryptography==1.7.1
dnspython==1.15.0
enum34==1.1.6
idna==2.7
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
monotonic==1.5
pyasn1==0.1.9
PyBluez==0.18
pycrypto==2.6.1
pygobject==3.22.0
PySocks==1.6.8
pyxdg==0.25
requests==2.19.1
RPi.GPIO==0.6.3
SecretStorage==2.3.1
six==1.11.0
sseclient==0.0.19
tzupdate==1.2.0
urllib3==1.23

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Baby - NO Basestation :)

### What did you do?
tried the example file arlo-streamingvideo.py

### What did you expect to see?
Anything actually ... 

### What did you see instead?
"list index out of range"
probably because I don't have a basestation. But I don't need a basestation to use the "Arlo Baby" camera. Is there a way to run arlo.StartStream without a basestation?
All of the other example files run perfectly as long as there is no need for a basestation. 
I already played around with arlobaby-nightlightcontrol.py and I can turn the light on and off :)

### Does this issue reproduce with the latest release?
yes

**Comment by jeffreydwalter** [comment]
The Arlo go and Arlo baby are both a basestation and a camera, so pass the
camera object as both arguments.

**Comment by Haskar** [comment]
awesome! thank you! 

Did I miss that anywhere in the documentation?

**Comment by jeffreydwalter** [comment]
Nah, the documentation needs work.
