### ISSUE TITLE
Non-chunked example doesn't work

### ISSUE THREAD

**Issue by allquixotic** [jeffreydwalter/arlo#78]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
CPython 3.7.0

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
Windows 10 64-bit

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
Just arlo and dependencies

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro 2

### What did you do?

The demo program in the README.md doesn't work if you comment out the chunked video download section and use `Arlo.GetRecording` instead. There appear to be two problems:

 - In the README.md sample code, `stream` raises `NameError` - I think you meant `video`
 - In arlo.GetRecording: 

```
 File "C:\Python37\lib\site-packages\Arlo.py", line 894, in GetRecording
    if chunk: video += chunk
TypeError: can only concatenate str (not "bytes") to str
```

### Does this issue reproduce with the latest release?

Yes

**Comment by jeffreydwalter** [comment]
@allquixotic please answer all the questions.

**Comment by jeffreydwalter** [comment]
Nevermind, I see the issue you are referring to. Fix it, thanks!
