### ISSUE TITLE
Calendar() succeeds but doesn't do anything

### ISSUE THREAD

**Issue by garethx** [jeffreydwalter/arlo#8]
Has anyone had any success with enabling the scheduled mode for a basestation? I call Calendar(), get a success response but it doesn't actually change the basestation mode. Arm and disarm both work fine, so I'm confused why this doesn't have any effect. I've compared it to what the Arlo app itself sends, and all seems fine.

**Comment by jeffreydwalter** [comment]
I'll try to test it out tomorrow. Been super busy moving.

**Comment by jeffreydwalter** [comment]
So, finally got a chance to look at this, and I'm seeing the Calendar() call return something strange.
```
{u'action': u'is', u'to': u'123-4567890_web', u'transId': u'web!d6312e4e.d0ed2!1490631706473', u'resource': u'schedule', u'from': u'1234567SA8901'}
```

In the browser I don't get that...

**Comment by garethx** [comment]
Same, although I'm not sure it's a problem. At least, I get a similar response back with the Arm/Disarm calls, but they still change the mode whereas Calendar seemingly does nothing.

**Comment by jeffreydwalter** [comment]
@garethx I figured out the issue... Turns out the boolean fields in the json MUST be actual bools, and not "true" or "false" strings. :/

I'll commit a fix here in a bit.

**Comment by jeffreydwalter** [comment]
@garethx Committed the fix. Calendar() should now work as expected. One note, I added a third argument to Calendar(). It's a boolean which allows you to set the calendar mode's active state to true or false. 
I noticed that the Arlo website is explicitly making a call to set calendar mode active=false when changing from calendar mode to some other mode, like armed.

Please do comment here and let me know how my fix works for you. Thanks!
