### ISSUE TITLE
support for arlo go

### ISSUE THREAD

**Issue by engel75** [jeffreydwalter/arlo#82]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
2.7.15

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
uname_result(system='Linux', node='xxxxxxxxxx', release='4.14.19-1-lts', version='#1 SMP Tue Feb 13 13:11:52 CET 2018', machine='x86_64', processor='')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
appdirs==1.4.3
arlo==1.1.7
asn1crypto==0.24.0
bcrypt==3.1.4
CacheControl==0.12.5
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
cryptography==2.3.1
distlib==0.2.7
distro==1.3.0
duplicity==0.7.17
ecdsa==0.13
enum34==1.1.6
fasteners==0.14.1
html5lib==1.0.1
idna==2.7
ipaddress==1.0.22
lockfile==0.12.2
monotonic==1.5
msgpack==0.5.6
packaging==17.1
paramiko==2.4.1
ply==3.11
progress==1.4
pyasn1==0.4.3
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
pyparsing==2.2.0
PySocks==1.6.8
pytoml==0.1.16
requests==2.19.1
retrying==1.3.3
six==1.11.0
sseclient==0.0.19
urllib3==1.23
webencodings==0.5.1
zenmap==7.70

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Go

### What did you do?
try do do and download fullframe screenshots

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

### What did you expect to see?
no error message

### What did you see instead?
as there is no basestation with arlo go devides I get:
"list index out of range" error message

### Does this issue reproduce with the latest release?
yes

**Comment by jeffreydwalter** [comment]
You need to pass the camera as both the camera and the basestation arguments. Arlo Go cameras are their own basestation. See https://github.com/jeffreydwalter/arlo/wiki/API-Documentation
