### ISSUE TITLE
failed to capture frame from opencv using arlo generated rstps stream url

### ISSUE THREAD

**Issue by bpecheux** [jeffreydwalter/arlo#84]
Hi
Using Python 2.7.13 in rapsbian kernel 4.14 on raspberry pi model 3 B with and arlo pro kit with one camera (camera firmware version 1.092.0.16_21159, basestation firmware version 1.10.0.8_22190). I have python-opencv installed and opencv '2.4.9.1'

I am trying to run the following script to connect to my arlo rtsps stream, grab a frame and save it to an image using python-opencv and arlo.
```
from Arlo import Arlo
import cv2

Connect to arlo network
arlo = Arlo('<username>','<password>')

# get arlo cameras
cameras = arlo.GetDevices('camera')

# Get arlo VideoStream url
stream_url = arlo.StartStream(basestations[0], cameras[0])

# Connect opencv to video stream
vs = cv2.VideoCapture(stream_url)

# wait a bit
time.sleep(2)

# grab a frame
(grabbed, frame) = vs.read()

# print if frame grab status
print(grabbed)

# save frame to image file
cv2.imwrite("test.jpg", frame)
```

I was expecting to be able to load the rtsps stream into opencv using cv2.VideoCapture("stream_url") but instead got grabbed returned as false, no frame and an imwrite error.

I did test the url coming of arlo.StartStream(basestations[0], cameras[0]) prior to using opencv with with ffmpeg using: 
```
ffmpeg -re -i '<rtsps_url>' -acodec copy -vcodec copy test.mp4
```
and I was successful at saving a mp4 video file from the arlo generated rtsps url. Not sure what I am doing wrong when using opencv. Wondering if some opencv specifics are required to be built. I was wondering if you would be able to share an example using arlo and opencv showing how to connect to an arlo generated rstps video stream.

Thanks

**Comment by jeffreydwalter** [comment]
@bpecheux please run this command and paste your results: `python -c "import cv2; print(cv2.getBuildInformation())" `

You should see this:
![image](https://user-images.githubusercontent.com/567047/44863906-02d3f900-ac44-11e8-8311-d7ea7cdbd9ff.png)

If not, rebuild opencv with ffmpeg.

**Comment by bpecheux** [comment]
Hi Jeffrey

Here is what I get:

```
  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  YES (ver 2.2.5)
    FFMPEG:                      YES
      codec:                     YES (ver 57.64.101)
      format:                    YES (ver 57.56.101)
      util:                      YES (ver 55.34.101)
      swscale:                   YES (ver 4.2.100)
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    Using libv4l (ver 1.12.3)
    XIMEA:                       NO
    Xine:                        NO
```
Do I need to match the version displayed on your screenshot? Also looks like I am missing the resample.

Thanks

**Comment by jeffreydwalter** [comment]
Do you have your PATH variable right? See here: https://stackoverflow.com/a/11703998/6138350

**Comment by jeffreydwalter** [comment]
oh... you have a logical error in the script you pasted. You're missing the call to get the basestations.

Does this work:
```
from Arlo import Arlo
import cv2

Connect to arlo network
arlo = Arlo('<username>','<password>')

# get arlo basestations
basestations = arlo.GetDevices('basestation')

# get arlo cameras
cameras = arlo.GetDevices('camera')

# Get arlo VideoStream url
stream_url = arlo.StartStream(basestations[0], cameras[0])

# Connect opencv to video stream
vs = cv2.VideoCapture(stream_url)

# wait a bit
time.sleep(2)

# grab a frame
(grabbed, frame) = vs.read()

# print if frame grab status
print(grabbed)

# save frame to image file
cv2.imwrite("test.jpg", frame)
```

**Comment by jeffreydwalter** [comment]
@bpecheux I just tested the above script on macOS and it worked fine. If the corrected script above doesn't work, then it's definitely got to be related to your setup.

**Comment by bpecheux** [comment]
OK let me retry it. Nope getting a grabbed= False so I guess it is the implementation of opencv on the pi. Will look for the PATH variables and update if successful. Thanks for your help.

**Comment by jeffreydwalter** [comment]
@bpecheux going to close this since I haven't heard back from you. If you need anything else, just comment here.
