### ISSUE TITLE
Is it possible to query battery level for a camera?

### ISSUE THREAD

**Issue by ajcooper72** [jeffreydwalter/arlo#85]
Exactly as the subject says - is the battery level exposed or is there a way to intercept the low battery notification?

Thanks

**Comment by jeffreydwalter** [comment]
Yes. Use the [GetCameraState(basestation)](https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L470) method if you just want to query the camera state. If you want to listen for battery low events, you will need to subscribe to the event stream and write some code to detect and handle those events. Take a look at the [SubscribeToMotionEvents()](https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L416) method for an example of how to subscribe to and handle a specific event type. Ultimately, if you want to handle your own events, you'll want to use the [HandleEvents()](https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L425) method and write all your own state machine to deal with any events you want to.
