### ISSUE TITLE
Can't combine Motion Events Subscription and Streaming Video together

### ISSUE THREAD

**Issue by ma-gu** [jeffreydwalter/arlo#88]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.14 :: Anaconda custom (64-bit)

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Windows', 'DS-Win', '2012ServerR2', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 79 Stepping 1, GenuineIntel')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
alabaster==0.7.10
anaconda-client==1.6.5
anaconda-navigator==1.6.9
anaconda-project==0.8.0
arlo==1.1.7
asn1crypto==0.22.0
astroid==1.5.3
astropy==2.0.2
azureml==0.2.7
babel==2.5.0
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.0.0
bokeh==0.12.10
boto==2.48.0
Bottleneck==1.2.1
bz2file==0.98
CacheControl==0.12.3
cdecimal==2.3
certifi==2017.11.5
cffi==1.10.0
chardet==3.0.4
click==6.7
cloudpickle==0.4.0
clyent==1.2.2
colorama==0.3.9
comtypes==1.1.2
conda==4.4.7
conda-build==3.0.27
conda-verify==2.0.0
configparser==3.5.0
contextlib2==0.5.5
cryptography==2.0.3
cycler==0.10.0
Cython==0.26.1
cytoolz==0.8.2
dask==0.15.3
datashape==0.5.4
decorator==4.1.2
distlib==0.2.5
distributed==1.19.1
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.12
Flask==0.12.2
Flask-Cors==3.0.3
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.1.1
gensim==3.1.0
gevent==1.2.2
glob2==0.5
greenlet==0.4.12
grin==1.2.1
h5py==2.7.0
heapdict==1.0.0
html5lib==0.999999999
idna==2.6
imageio==2.2.0
imagesize==0.7.1
ipaddress==1.0.18
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==7.0.0
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
jupyterlab==0.27.0
jupyterlab-launcher==0.4.0
keyring==10.6.0
lazy-object-proxy==1.3.1
llvmlite==0.20.0
locket==0.2.0
lockfile==0.12.2
lxml==4.1.0
MarkupSafe==1.0
matplotlib==2.1.0
mccabe==0.6.1
menuinst==1.4.10
mistune==0.7.4
monotonic==1.5
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
mxnet==0.7.0
navigator-updater==0.1.0
nb-anacondacloud==1.4.0
nb-conda==2.2.0
nb-conda-kernels==2.1.0
nbconvert==5.3.1
nbformat==4.4.0
nbpresent==3.0.2
networkx==2.0
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numba==0.35.0+10.g143f70e.dirty
numexpr==2.6.2
numpy==1.14.0
numpydoc==0.7.0
odo==0.5.1
olefile==0.44
openpyxl==2.4.8
packaging==16.8
pandas==0.22.0
pandocfilters==1.4.2
partd==0.3.8
path.py==10.3.1
pathlib2==2.3.0
patsy==0.4.1
pep8==1.7.0
pickleshare==0.7.4
Pillow==4.2.1
pkginfo==1.4.1
ply==3.10
progress==1.3
prompt-toolkit==1.0.15
psutil==5.4.0
psycopg2==2.7.3.2
py==1.4.34
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0
pydocumentdb==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.4
pyodbc==4.0.17
pyOpenSSL==17.2.0
pyparsing==2.2.0
PySocks==1.6.7
pytest==3.2.1
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==0.5.2
pywin32==221
pywin32-ctypes==0.1.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.18.4
rope==0.10.5
ruamel-yaml==0.11.14
scandir==1.6
scikit-image==0.13.0
scikit-learn==0.19.1
scipy==0.19.1
seaborn==0.8
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
smart-open==1.5.3
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.4
SQLAlchemy==1.1.13
sseclient==0.0.19
statsmodels==0.8.0
subprocess32==3.2.7
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
wget==3.2
widgetsnbextension==3.0.2
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11
xgboost==0.7
xlrd==1.1.0
XlsxWriter==1.0.2
xlwings==0.11.4
xlwt==1.3.0
zict==0.1.3

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Pro2 + basestation

### What did you do?
I'm just trying to start video streaming once motion detection happens in the folloi
If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

from Arlo import Arlo
from subprocess import call
from datetime import datetime
from time import strftime

USERNAME = 'xxx'
PASSWORD = 'xxx'

def main():
    arlo = Arlo(USERNAME, PASSWORD)
    basestations = arlo.GetDevices('basestation')
    arlo.SetMotionAlertsOn(basestations[0], 100)
    arlo.SubscribeToMotionEvents(basestations[0], handleMotion)

def handleMotion(arlo, event):
    print("motion detected!")
    print(event)
    cameras = arlo.GetDevices('camera')
    basestations = arlo.GetDevices('basestation')
    arlo.Subscribe(basestations[0])
    url = arlo.StartStream(basestations[0], cameras[0])
    print("streaming from:" + url)
    call(['ffmpeg', '-re', '-i', url, '-t', '25' '-acodec', 'copy', '-vcodec', 'copy', datetime.now().strftime('%Y-%m-%d %H_%M_%S') + '.mp4'])

### What did you expect to see?
I expected to see output from ffmpeg - which works fine as a separate code sample from wiki.

### What did you see instead?
The following stack trace:

Traceback (most recent call last):
  File "module1.py", line 51, in <module> (*this line number is irrelevant though - provided code a little bit different*)
    main()
  File "module1.py", line 24, in main
    arlo.HandleEvents(basestations[0], callback)
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 447, in HandleEvents
    response = callback(self, event)
  File "module1.py", line 35, in callback
    url = arlo.StartStream(basestations[0], cameras[0])
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 964, in StartStream
    return self.TriggerAndHandleEvent(basestation, trigger, callback)
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 462, in TriggerAndHandleEvent
    trigger(self)
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 956, in trigger
    nl.stream_url_dict = self.request.post('https://arlo.netgear.com/hmsweb/users/devices/startStream', {"to":camera.get
('parentId'),"from":self.user_id+"_web","resource":"cameras/"+camera.get('deviceId'),"action":"set","responseUrl":"", "p
ublishResponse":True,"transId":self.genTransId(),"properties":{"activityState":"startUserStream","cameraId":camera.get('
deviceId')}}, headers={"xcloudId":camera.get('xCloudId')})
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 157, in post
    return self._request(url, 'POST', params, headers, raw)
  File "C:\Anaconda\lib\site-packages\Arlo.py", line 148, in _request
    raise HTTPError('Request ({0} {1}) failed'.format(method, url), response=r)
requests.exceptions.HTTPError: Request (POST https://arlo.netgear.com/hmsweb/users/devices/startStream) failed

### Does this issue reproduce with the latest release?
Yes

Help is very appreciated.

**Comment by jeffreydwalter** [comment]
```
from Arlo import Arlo
from subprocess import call
from datetime import datetime
from time import strftime

USERNAME = 'xxx'
PASSWORD = 'xxx'

# This is a nice helper function for printing JSON.
def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

def handleMotion(arlo, event):
    print("motion detected!")
    pp(event)
    url = arlo.StartStream(basestations[0], cameras[0])
    print("streaming from:" + url)
    call(['ffmpeg', '-re', '-i', url, '-t', '25' '-acodec', 'copy', '-vcodec', 'copy', datetime.now().strftime('%Y-%m-%d %H_%M_%S') + '.mp4'])

def main():
    try:
        arlo = Arlo(USERNAME, PASSWORD)
        # If you don't expect the list of basestations and cameras to change,
        # you can get them once here and reuse them.
        basestations = arlo.GetDevices('basestation') 
        cameras = arlo.GetDevices('camera')

        # Please include the JSON from both of the following pp() statements in your reply.
        # I suspect cameras[0] might be offline or something like that. 
        pp(basestations)
        pp(cameras)

        arlo.SetMotionAlertsOn(basestations[0], 100)
        arlo.SubscribeToMotionEvents(basestations[0], handleMotion)
    except Exception as e:
       # I think this should work to get you a little more info about the failure.
        print(e.response.status_code)
        print(e.response.reason)
        print(e.response.headers)
```

**Comment by ma-gu** [comment]
Thanks for you help, I've got an idea how to get more details on failure. 

Here's basestations/cameras dump - nothing suspicious though:

```
[
    {
        "arloMobilePlan": false,
        "automationRevision": 0,
        "connectivity": {
            "connected": true,
            "mepStatus": "unknown",
            "type": "ethernet"
        },
        "dateCreated": 1536761477172,
        "deviceId": "XXXxxxXXXxxxx",
        "deviceName": "Kitchen",
        "deviceType": "basestation",
        "displayOrder": 2,
        "firmwareVersion": "1.10.0.8_22190",
        "interfaceSchemaVer": "7",
        "interfaceVersion": "i005",
        "lastModified": 1537385756420,
        "mediaObjectCount": 0,
        "migrateActivityZone": false,
        "modelId": "VMB4000",
        "owner": {
            "firstName": "FirstName",
            "lastName": "LastName",
            "ownerId": "XXXXXXX-YYY-ZZZZZZZZ"
        },
        "properties": {
            "hwVersion": "VMB4000r3",
            "modelId": "VMB4000",
            "olsonTimeZone": "America/Los_Angeles"
        },
        "state": "provisioned",
        "uniqueId": "XXXXXXX-YYY-ZZZZZZZZ_XXXxxxXXXxxxx",
        "userId": "XXXXXXX-YYY-ZZZZZZZZ",
        "userRole": "OWNER",
        "xCloudId": "xCloudId"
    }
]

[
    {
        "arloMobilePlan": false,
        "cvrEnabled": false,
        "dateCreated": 1536761579135,
        "deviceId": "5G71867MAE294",
        "deviceName": "Left",
        "deviceType": "camera",
        "displayOrder": 1,
        "interfaceSchemaVer": "1",
        "interfaceVersion": "i002",
        "lastImageUploaded": "true",
        "lastModified": 1537385756905,
        "mediaObjectCount": 2,
        "migrateActivityZone": false,
        "modelId": "VMC4030P",
        "owner": {
            "firstName": "FirstName",
            "lastName": "LastName",
            "ownerId": "XXXXXXX-YYY-ZZZZZZZZ"
        },
        "parentId": "parentId",
        "presignedFullFrameSnapshotUrl": "https://arlos3-prod-z2.s3.amazonaws.com/.../.../.../fullFrameSnapshot.jpg?AWSAccessKeyId=AWSAccessKeyId&Expires=1537472156&Signature=e2tNQOIYLLnF3yuhXRDHvWMiiJA%3D",
        "presignedLastImageUrl": "https://arlolastimage-z2.s3.amazonaws.com/.../.../.../lastImage.jpg?AWSAccessKeyId=AWSAccessKeyId&Expires=1537472156&Signature=s8Ino0bD6C3xTw8n5PNCd8Q%2FIxA%3D",
        "presignedSnapshotUrl": "https://arlos3-prod-z2.s3.amazonaws.com/.../.../.../snapshot.jpg?AWSAccessKeyId=AWSAccessKeyId&Expires=1537472156&Signature=9AUHgoi7oUFtt2MTNY7MU%2BBoCAs%3D",
        "properties": {
            "hwVersion": "H3",
            "modelId": "VMC4030P",
            "olsonTimeZone": "America/Los_Angeles"
        },
        "state": "provisioned",
        "uniqueId": "XXXXXXX-YYY-ZZZZZZZZ_XXXxxxXXXxxxx",
        "userId": "XXXXXXX-YYY-ZZZZZZZZ",
        "userRole": "OWNER",
        "xCloudId": "xCloudId"
    }
]
```
As I figured out necessary details I think it's OK to close an issue. Thanks again!

**Comment by jeffreydwalter** [comment]
I'm thinking the basestation and camera objects aren't available in your callback.

Try this:
```
from Arlo import Arlo
from subprocess import call
from datetime import datetime
from time import strftime

USERNAME = 'xxx'
PASSWORD = 'xxx'

# This is a nice helper function for printing JSON.
def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

def handleMotion(arlo, event):
    print("motion detected!")
    pp(event)
    # Does this print the basestation and camera JSON? If no, that is your problem and you'll need to create a closure so they are available here.
    pp(basestations)
    pp(cameras)
    url = arlo.StartStream(basestations[0], cameras[0])
    print("streaming from:" + url)
    call(['ffmpeg', '-re', '-i', url, '-t', '25' '-acodec', 'copy', '-vcodec', 'copy', datetime.now().strftime('%Y-%m-%d %H_%M_%S') + '.mp4'])

def main():
    try:
        arlo = Arlo(USERNAME, PASSWORD)
        # If you don't expect the list of basestations and cameras to change,
        # you can get them once here and reuse them.
        basestations = arlo.GetDevices('basestation') 
        cameras = arlo.GetDevices('camera')

        arlo.SetMotionAlertsOn(basestations[0], 100)
        arlo.SubscribeToMotionEvents(basestations[0], handleMotion)
    except Exception as e:
       # I think this should work to get you a little more info about the failure.
        print(e.response.status_code)
        print(e.response.reason)
        print(e.response.headers)
```
