### ISSUE TITLE
"basestring is not defined" - problem with python 3.x

### ISSUE THREAD

**Issue by burken-** [jeffreydwalter/arlo#89]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Version: 3.6.6

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
system='Linux', release='4.15.0-34-generic', version='#37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018', machine='x86_64', processor='x86_64'

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
appdirs==1.4.3
arlo==1.1.7
asn1crypto==0.24.0
asyncio==3.4.3
bcrypt==3.1.4
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.3.1
Flask==1.0.2
gunicorn==19.9.0
idna==2.7
itsdangerous==0.24
Jinja2==2.10
lxml==4.2.5
MarkupSafe==1.0
monotonic==1.5
oauthlib==2.1.0
packaging==17.1
paho-mqtt==1.4.0
paramiko==2.4.2
pkg-resources==0.0.0
power==1.4
pyasn1==0.4.4
pycparser==2.19
PyNaCl==1.2.1
pynut2==2.1.2
pyparsing==2.2.1
PySocks==1.6.8
python-magic==0.4.15
requests==2.19.1
requests-oauthlib==1.0.0
six==1.11.0
sseclient==0.0.19
tellduslive==0.10.4
telnetlib3==1.0.0
urllib3==1.23
wakeonlan==1.1.6
wcwidth==0.1.7
websocket-client==0.53.0
Werkzeug==0.14.1

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
* Arlo basestation pro (VMB4000)
* Arlo wirefree
* Arlo Q Plus (VMC3040S)

### What did you do?
Trying to record for X seconds and then logout

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)
```
from Arlo import Arlo
USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'
CAMERAID = 'camera to record from'

try:
    # Login to Arlo
    arlo = Arlo(USERNAME, PASSWORD)

    # Fetch all devices
    devices = arlo.GetDevices()
    
    # Get the camera to use for recording
    camera = next(x for x in devices if x['deviceId'] == CAMERAID)

    # Get the basestation
    if(camera['deviceId'] != camera['parentId']):
        basestation = next((x for x in devices if (x['deviceId'] == camera['parentId'])), None)
    else:
	# In case of Arlo Q where the camera is also the basestation
        basestation = camera
    
    # Make the recording
    arlo.StartRecording(basestation, camera)
    time.sleep(10)
    arlo.StopRecording(camera)
	
    arlo.Logout()
    print('Recording completed')
	
except Exception as e:
    print(e):
```
### What did you expect to see?
Expected result would be the printed text "Recording completed"

### What did you see instead?
An exception stating:
 File "/var/www/automate/env/lib/python3.6/site-packages/Arlo.py", line 321, in Unsubscribe
    if isinstance(basestation, (basestring, str, unicode)):
NameError: name 'basestring' is not defined

This is thrown when calling logout which in turn calls unsubscribe.

### Does this issue reproduce with the latest release?
I belive I'm running the latest release

**Comment by jeffreydwalter** [comment]
@burken- I don't have any Arlo Q cameras. Please use pip to upgrade to the latest arlo package and let me know if that fixes your bug. Thanks!

**Comment by burken-** [comment]
The six-package did the trick, works like a charm!
