### ISSUE TITLE
type issue on stable as well as latest

### ISSUE THREAD

**Issue by RobertLHarris** [jeffreydwalter/arlo#90]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide the steps you took to reproduce the issue. 
A complete runnable program is good. (don't include your user/password or any sensitive info)

**Comment by RobertLHarris** [comment]
**Python Version:**  3.6.6

**python3 -c 'import platform; print(platform.uname());'**
uname_result(system='Linux', node='camel', release='4.15.0-33-generic', version='#36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018', machine='x86_64', processor='x
86_64')

**pip3 freeze:**
arlo==1.1.8
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
bottle==0.12.13
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
distro-info==0.18
docker==2.5.1
docker-pycreds==0.2.1
fail2ban==0.10.2
Glances==2.11.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
influxdb==4.1.1
isc==2.0
Jinja2==2.10
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
MarkupSafe==1.0
matplotlib==2.1.1
monotonic==1.5
motioneye==0.39.3
netifaces==0.10.4
numpy==1.13.3
olefile==0.45.1
PAM==0.4.2
Pillow==5.2.0
ply==3.11
psutil==5.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycodestyle==2.3.1
pycparser==2.18
pycrypto==2.6.1
pycryptodomex==3.4.7
pycurl==7.43.0.2
pygobject==3.26.1
pyinotify==0.9.6
pyOpenSSL==17.5.0
pyparsing==2.2.0
pyserial==3.4
pysmi==0.2.2
pysnmp==4.4.3
PySocks==1.6.8
pystache==0.5.4
python-apt==1.6.2
python-dateutil==2.6.1
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
six==1.11.0
sseclient==0.0.19
ssh-import-id==5.7
systemd-python==234
tornado==5.1.1
Twisted==17.9.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
websocket-client==0.44.0
xattr==0.9.2
zope.interface==4.3.2

**Camera: Arlo Pro**
```
# Get all of the recordings for a date range.
print('Pre-Library Pull')
print('  '+seven_days_ago, "is of type' + type(seven_days_ago))
print('  '+today, "is of type", type(today))
library = arlo.GetLibrary( seven_days_ago, today )
print('Library: '+library)           
```
From tthe output you can see the types are str and not list but I'm getting an error when I call the "arlo.GetLibrary" function. 
Pre-Library Pull                                                                                                                                               20180918 is of type <class 'str'>                                                                                                                            20180925 is of type <class 'str'>                                                                                                                          must be str, not list                                                                                                                                                                              

If I try to pass something like:
    range = sevendays_ago+', 'today'
    library = arlo.GetLibrary( range )

it complains it needs 2 arguments, not one.

I have tried on both master and stable.

**Comment by jeffreydwalter** [comment]
Can you please include the full script you are running? Please make sure to format it properly as a code block.

**Comment by RobertLHarris** [comment]
Here's the one I'm getting the error on.  I'm not sure how to the code block.  Here's a pastebin of the script ( one of the samples on your site ) https://pastebin.com/v0MQrFrb and a gzip.

[Get_Arlo_Videos.py.gz](https://github.com/jeffreydwalter/arlo/files/2420751/Get_Arlo_Videos.py.gz)

**Comment by jeffreydwalter** [comment]
You make a code block here by using three backticks on their own line, followed by your code, followed by a closing three more backticks.

Your problem is in your print statement. You can't concatenate `library` to a string, because it's a `list` (i.e., dictionary like this []).

Try this:
```
#!/usr/bin/python3
 
# Install base code from: https://github.com/jeffreydwalter/arlo
# pip install arlo
 
from Arlo import Arlo
 
from datetime import timedelta, date
import datetime
import sys
 
USERNAME = 'robert.l.harris@gmail.com'
PASSWORD = 'R4nd0mP4sswd'
 
try:
    # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    print('Logging in '+USERNAME)
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.
 
    today = (date.today()-timedelta(days=0)).strftime("%Y%m%d")
    seven_days_ago = (date.today()-timedelta(days=7)).strftime("%Y%m%d")
    print('Getting from '+seven_days_ago+' until '+today)

    # Get all of the recordings for a date range.
    library = arlo.GetLibrary( seven_days_ago, today )
    print(library)
 
    # Iterate through the recordings in the library.
    for recording in library:
 
        print('Getting recording '+recording+' from '+recording['createdDate']+' and saving as '+videofilename+'.')
        videofilename = datetime.datetime.fromtimestamp(int(recording['name'])//1000).strftime('%Y-%m-%d %H-%M-%S') + ' ' + recording['uniqueId'] + '.mp4'
        ##
        # The videos produced by Arlo are pretty small, even in their longest, best quality settings,
        # but you should probably prefer the chunked stream (see below).
        ###    
        #    # Download the whole video into memory as a single chunk.
        #    video = arlo.GetRecording(recording['presignedContentUrl'])
        #    with open('videos/'+videofilename, 'wb') as f:
        #        f.write(video)
        #        f.close()
        # Or:
        #
        # Get video as a chunked stream; this function returns a generator.
        stream = arlo.StreamRecording(recording['presignedContentUrl'])
        with open('~/Arlo/videos/'+videofilename, 'wb') as f:
            for chunk in stream:
                f.write(chunk)
                #f.write(join(chunk))
            f.close()
 
        print('Downloaded video '+videofilename+' from '+recording['createdDate']+'.')
 
    # Delete all of the videos you just downloaded from the Arlo library.
    # Notice that you can pass the "library" object we got back from the GetLibrary() call.
#   result = arlo.BatchDeleteRecordings(library)
 
    # If we made it here without an exception, then the videos were successfully deleted.
    print('Batch deletion of videos completed successfully.')
 
except Exception as e:
    print(e)
```
