### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by sdorilas** [jeffreydwalter/arlo#96]
Please answer these questions before submitting your issue. Thanks!

### What version of Python are you using (`python -V`)?
Python 2.7.10

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?

('Darwin', 'home.local', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64', 'x86_64', 'i386')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
ltgraph==0.10.2
arlo==1.1.8
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2018.10.15
chardet==3.0.4
idna==2.7
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
monotonic==1.5
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
PySocks==1.6.8
python-dateutil==1.5
pytz==2013.7
requests==2.20.0
scipy==0.13.0b1
six==1.4.1
sseclient==0.0.19
urllib3==1.24.1
vboxapi==1.0
xattr==0.6.4

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
Arlo Wirefree Basestation H11. (4)

### What did you do?

I am still trying to get streaming or snapshots working on Homekit. It worked for 2 of my 4 cameras prior to installing this but now nothing works at all. 

### What did you expect to see?
Live feed on my cameras

### What did you see instead?
The snapshot from when I first run homebridge

### Does this issue reproduce with the latest release?
yes

**Comment by jeffreydwalter** [comment]
Can you please provide an example script the reproduces your problem?

**Comment by sdorilas** [comment]
I'm not really sure what you mean. I'm running through Homebridge. Guess my next question should be, what am I missing? I haven't installed the your Arlo library but i'm not sure how to.  I completed Note 1 but not note 2

 {
 		"name": "Backyard",
 		"videoConfig": {
 			"source": "-re -i rtsp://myfancy_rtsp_stream",
 			"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
 			"maxStreams": 2,
 			"maxWidth": 1280,
 			"maxHeight": 720,
 			"maxFPS": 30

**Comment by jeffreydwalter** [comment]
I don't use Homebridge, so I don't really know how that works. If you could please provide more information about the problem you're having and how I can reproduce it, I would be happy to help you.

**Comment by sdorilas** [comment]
Okay,  no problem. Homebridge aside — is there a guide for Arlo cameras  through HomeKit

**Comment by jsm174** [comment]
@sdorilas - Look at devarshi's fork of homebridge-camera-ffmpeg: https://github.com/devarshi/homebridge-camera-ffmpeg

**Comment by jeffreydwalter** [comment]
@jsm174 thanks for pointing that out!

**Comment by sdorilas** [comment]
@jsm174 That’s where I started, then for Arlo cameras I ended up here. I have to install Jeffrey Walter’s Arlo Library, that’s where I’m at currently. I ran pip install Arlo — I’m not sure where or how to configure the library.

**Comment by jsm174** [comment]
You don't need to "configure the library".  Your homebridge's `config.json` sets it all up. If you look at that readme: 

```
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
      	"source": "arlo",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30,
      	"maxBitrate": 300,
      	"vcodec": "copy",
      	"audio": false,
      	"debug": true,
        "arloUserName": "email@provider.com",
        "arloPassword": "<your arlo password>",
        "arloCameraIndex": "0"
      }
    }
  ]
}
```

**Comment by sdorilas** [comment]
Got it! Having same issue. This camera is not responding if I try to view a camera. I can hear the camera click and I see the following on homebridge:
[2018-11-6 22:16:58] [Arlo] Snapshot skipped: Camera 4WA16C7TCADF7 [4WA16C7TCADF7] - Next in 123 secs
[2018-11-6 22:16:58] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 123 secs
[2018-11-6 22:16:58] [Arlo] Snapshot skipped: Camera 4N71697P26213 [4N71697P26213] - Next in 126 secs
[2018-11-6 22:16:59] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 122 secs
[2018-11-6 22:16:59] [Arlo] Snapshot skipped: Camera 4WA16C7TCADF7 [4WA16C7TCADF7] - Next in 122 secs
[2018-11-6 22:16:59] [Arlo] Snapshot skipped: Camera 4N71697P26213 [4N71697P26213] - Next in 124 secs
[2018-11-6 22:17:00] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 121 secs
[2018-11-6 22:17:02] [Arlo] prepareStream
[2018-11-6 22:17:13] [Arlo] handleStreamRequest

**Comment by jeffreydwalter** [comment]
@sdorilas just pushed a fix for this issue. Please give it a try when you can and let me know how it goes. Thanks!

**Comment by RSickenberg** [comment]
I have this issue 

`error : Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-camera-ffmpeg/arlo.py", line 4, in <module>
    from Arlo import Arlo
ImportError: No module named Arlo`

**Comment by jeffreydwalter** [comment]
@RSickenberg `from arlo import Arlo` not `from Arlo import Arlo`. The import changed a while back.

**Comment by RSickenberg** [comment]
@jeffreydwalter Like said early, even with `Arlo => arlo`
