### ISSUE TITLE
Heartbeat thread terminates on network problems

### ISSUE THREAD

**Issue by manluk** [jeffreydwalter/arlo#98]
If there are network problems while the heartbeat thread tries to send the ping to the arlo service, the heartbeat thread terminates. To prevent this I added the following lines to Arlo.py after line 307:

```
                except Exception as e:
                    pass
```

The modified Heartbeat method now looks like this:

```
        def Heartbeat(self, stop_event):
            while not stop_event.wait(30.0):
                try:
                    self.Ping(basestation)
                except queue.Empty:
                    pass
                except Exception as e:
                    pass
```

Could you add this error handling to your code?

**Comment by jeffreydwalter** [comment]
Seems reasonable. Can you please make a pull request for this?

**Comment by jeffreydwalter** [comment]
@manluk what is the specific exception you are seeing when there's a network issue? After thinking about this a little more, I'd hate to mask all exceptions like that.

**Comment by jeffreydwalter** [comment]
I went ahead and implemented your suggestion for now. I would like to know the exact exception you're seeing though. Thanks!
