### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Phoenix-DH** [jeffreydwalter/arlo#99]
### What version of Python are you using (`python -V`)?
2.7.13

### What operating system and processor architecture are you using (`python -c 'import platform; print(platform.uname());'`)?
('Linux', 'phoenixpi', '4.14.71-v7+', '#1145 SMP Fri Sep 21 15:38:35 BST 2018', 'armv7l', '')

### Which Python packages do you have installed (run the `pip freeze` or `pip3 freeze` command and paste output)?
arlo==1.1.8
certifi==2018.10.15
chardet==3.0.4
cryptography==1.7.1
enum34==1.1.6
idna==2.7
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
monotonic==1.5
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
PySocks==1.6.8
pyxdg==0.25
requests==2.20.1
RPi.GPIO==0.6.3
SecretStorage==2.3.1
six==1.10.0
sseclient==0.0.22
urllib3==1.24.1

### Which Arlo hardware do you have (camera types - [Arlo, Pro, Q, etc.], basestation model, etc.)?
2 * Arlo Pro | 1 * Arlo Pro 2

### What did you do/Expect?
I am running homebridge with homebridge-arlo and homebridge-camera-ffmpeg plugin.
I want to have a live video inside homekit.

Static images are working. But for video I get the following result when running the following:
```
[2018-11-27 07:59:37] [Camera-ffmpeg] Start streaming video from Esszimmer with 1280x720@299kBit
ffmpeg -rtsp_transport tcp -re -i rtsps://vzwow64-z1-prod.vz.netgear.com:443/vzmodulelive/XXX_YYY?egressToken=TOKEN\&userAgent=iOS\&cameraId=CAMERA -map 0:1 -vcodec copy -f rawvideo -tune zerolatency -payload_type 99 -ssrc 6472992 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params B6y+3qb8/aJ46zhD78j6sk43gtKZ4d801dfx+3zl srtp://ARLO:PORT?rtcpport=PORT\&localrtcpport=PORT\&pkt_size=1316
```

Result:
`rtsps://XXX?egressToken=XXX&userAgent=iOS&cameraId=XXX: Operation not permitted`

I am not sure to which component this issue belongs to.
But I can imagine to the library.

Thank you!

**Comment by jeffreydwalter** [comment]
I just tested and streaming video works fine for me. Please open an issue with the homebridge library.

**Comment by Phoenix-DH** [comment]
Okay, thank you!
Means must have something to do with homebridge itself.

Can I add something to make it clearer?

Thanks

**Comment by jeffreydwalter** [comment]
I think what you wrote is pretty clear. I believe the issue is related to the ffmpeg command that's being used, but I'm not an expert in ffmpeg.

**Comment by Phoenix-DH** [comment]
Thank you!
